### ISSUE TITLE
Agent does not pull used memory from containers on Raspberry Pi 4b

### ISSUE THREAD

**Issue by ionyx0** [henrygd/beszel#10]
Thanks for a great piece of software!  I will be switching to this from the heavy Prometheus/Grafana/InfluxDB stack soon.

Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 6.6.28+rpt-rpi-v8
Architecture: arm64

Docker version 20.10.24+dfsg1, build 297e128

Data retrieved from agent:
```[
  {
    "c": 0.19,
    "m": 0,
    "n": "prometheus"
  },
  {
    "c": 0.1,
    "m": 0,
    "n": "adguard_exporter"
  },
  {
    "c": 0.08,
    "m": 0,
    "n": "glances"
  },
  {
    "c": 0.71,
    "m": 0,
    "n": "dockge_dockge_1"
  },
  {
    "c": 0.04,
    "m": 0,
    "n": "grafana"
  },
  {
    "c": 0.01,
    "m": 0,
    "n": "beszel-agent"
  },
  {
    "c": 0.13,
    "m": 0,
    "n": "node_exporter"
  }
]
```

The containers are obviously running because of the CPU usage in the response but there is no memory being reported back in the response.

I haven't found anything in the logs that indicate an obvious error retrieving data.  Let me know if there's any further info I can provide.

**Comment by henrygd** [comment]
This is probably due to the specific docker version and differences in the API.

If you could do the following it would be very helpful:

1. Run `docker ps` to list your running containers, then choose a container ID.
2. Make a request to the API for the container resource usage (replace `d07d19594b6e` with your container ID):
```
curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" "http://localhost/containers/d07d19594b6e/stats?stream=0&one-shot=1"
```
3. Post the whole response here, or just the "memory_stats" section.

Thanks!

**Comment by ionyx0** [comment]
Thanks for the reply... After running the curl you sent using a container ID from my instance, it looks like this isn't an issue with your code.  _Every_ value in the `memory_stats` object is a `0`.  I will do some research on why this isn't populated in this scenario (RPi 4b + docker 20.10)

Here's the `memory_stats` object for posterity:
```
  "memory_stats": {
    "stats": {
      "active_anon": 0,
      "active_file": 0,
      "anon": 0,
      "anon_thp": 0,
      "file": 0,
      "file_dirty": 0,
      "file_mapped": 0,
      "file_writeback": 0,
      "inactive_anon": 0,
      "inactive_file": 0,
      "kernel_stack": 0,
      "pgactivate": 0,
      "pgdeactivate": 0,
      "pgfault": 0,
      "pglazyfree": 0,
      "pglazyfreed": 0,
      "pgmajfault": 0,
      "pgrefill": 0,
      "pgscan": 0,
      "pgsteal": 0,
      "shmem": 0,
      "slab": 0,
      "slab_reclaimable": 0,
      "slab_unreclaimable": 0,
      "sock": 0,
      "thp_collapse_alloc": 0,
      "thp_fault_alloc": 0,
      "unevictable": 0,
      "workingset_activate": 0,
      "workingset_nodereclaim": 0,
      "workingset_refault": 0
    }
  }
```

**Comment by ionyx0** [comment]
FYI, the changes to `/boot/firmware/cmdline.txt` to enable the memory cgroup works.  Thanks for the quick reply and the awesome software!

**Comment by henrygd** [comment]
Awesome, good to hear.
