### ISSUE TITLE
Feature Request: Handling Gaps in Graphs for Unreachable Agents/Hosts

### ISSUE THREAD

**Issue by svenvg93** [henrygd/beszel#100]
Currently, when an agent/host is down or unreachable, the graphs do not indicate the missed data; instead, they close the gap, creating a continuous line. It would be beneficial to modify the graphs to leave a visible gap whenever data collection intervals are failed. This would more accurately reflect periods of downtime or inaccessibility, making it easier to identify when an agent/host was not collecting data as expected. This would more accurately reflect periods of downtime or inaccessibility, making it easier to identify issues.

**Comment by henrygd** [comment]
I agree this would be better. I'll add it soonish if it's an easy change through the chart library.

**Comment by crypt0rr** [comment]
It is somewhere in line with this in my graphs, currently running v0.1.2. The interesting part is, the agent is running on the same host as the lab, both in containers.

<img width="1357" alt="Screenshot 2024-08-09 at 10 59 51" src="https://github.com/user-attachments/assets/ea5e56e8-37bc-4fa8-a255-15e8f660de02">

**Comment by henrygd** [comment]
@crypt0rr That doesn't look right. I think you may be experiencing the same issue as #58, where older versions of the Docker API are not reliably returning info for all containers.

What's your output of `docker version`? So far I've only seen this on Docker 24 / API 1.43.

I recommend upgrading to Docker Engine 27 if possible.

**Comment by crypt0rr** [comment]
@henrygd Excuse for my late reply. Indeed I'm running version `24.0.5` on `Ubuntu 24.04 LTS` - will do the upgrade.
