### ISSUE TITLE
[BUG] System host name with # or space (maybe other special chars) does not works.

### ISSUE THREAD

**Issue by scriptzteam** [henrygd/beszel#102]
Hi,
today when added system host name with # and space it broken.

See gif below.

![hy1AJMWdf7-b](https://github.com/user-attachments/assets/80dfa3df-31e1-4267-9add-965c01a4c544)

**Comment by henrygd** [comment]
Thanks for pointing this out.

I assume it's still collecting data but the routing is broken. Hopefully an easy fix for the next release.
