### ISSUE TITLE
Docker Hosts - Agent reports system as down if any container is stuck in a boot loop

### ISSUE THREAD

**Issue by NightHawkATL** [henrygd/beszel#103]
Noticed this yesterday with 2 of my Docker VMs. Also got word from another Discord member that is running this as well that the same thing happened to him.

For me, I had an issue with the redis container for Tube Archivist that made it stick in a boot loop as it couldn't read the cache db after an update. Once I cleared the cache db and restarted the container, the Beszel agent started reporting the whole VM and all containers to be up. 

For my friend, he had an issue with cloudflared and was stuck in a boot loop. He stopped the container and the agent reported the VM as up again.

**Comment by henrygd** [comment]
I'll look into it. Should be an easy enough fix.

**Comment by theRealBassist** [comment]
> Noticed this yesterday with 2 of my Docker VMs. Also got word from another Discord member that is running this as well that the same thing happened to him.
> 
> For me, I had an issue with the redis container for Tube Archivist that made it stick in a boot loop as it couldn't read the cache db after an update. Once I cleared the cache db and restarted the container, the Beszel agent started reporting the whole VM and all containers to be up.
> 
> For my friend, he had an issue with cloudflared and was stuck in a boot loop. He stopped the container and the agent reported the VM as up again.

This was  exactly what was causing my problem in #57 . TubeArchivist had a Redis issue, and at the same time I was trying to get Beszel to work. When I fixed the TubeArchivist issue is when I restarted my VM and everything was working.
