### ISSUE TITLE
Show agent versions on hub.

### ISSUE THREAD

**Issue by utlilb** [henrygd/beszel#105]
It would be nice to see the agent versions of each connected system.

**Comment by henrygd** [comment]
Added in 0.2.0

**Comment by hellofaduck** [comment]
I updated docker image of server-side and all agents on all hosts to 0.2.0, and still no agent version info...
![image](https://github.com/user-attachments/assets/cebb82d6-5c4e-4e01-ac5b-02684b1e8d80)

**Comment by henrygd** [comment]
@hellofaduck Please double check that agents are updated to 0.2.0 and restart them.

If you use the binary and have a system service running, make sure to restart the service:

```bash
sudo systemctl restart beszel-agent
```

In the "systems" table in PocketBase you should see the agent version (`v`) being populated:

![image](https://github.com/user-attachments/assets/99a81692-8ab5-42b4-822e-c66f19bb5f88)

**Comment by hellofaduck** [comment]
It seems that restarting of agents is worked, but strange that update command dont doing that automaticaly....
