### ISSUE TITLE
Add iFrame support

### ISSUE THREAD

**Issue by nooz** [henrygd/beszel#112]
For use inside other dashboards e.g. Organizr

Thanks

**Comment by henrygd** [comment]
Do you use a reverse proxy? If so, you should be able to delete or override the `X-Frame-Options` header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

I don't want to remove the header by default, so I'll need to add an env var or command line argument to override it directly in a future release.

**Comment by utlilb** [comment]
I tested adding the X-Frame-Options header and it works correctly. If it doesn't work for you also check on CSP directives. This is the modern replacement for x-frame. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by lephtHanded** [comment]
> I tested adding the X-Frame-Options header and it works correctly. If it doesn't work for you also check on CSP directives. This is the modern replacement for x-frame.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

from a person with almost no HTML experience, how did you get this to work?

**Comment by henrygd** [comment]
I added the `CSP` environment variable in 0.5.0 to allow doing this directly.

You should be able to do something like `CSP="frame-ancestors https://example.com"`.

Let me know if you have any questions.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Comment by uaoao** [comment]
A suggestion, you can add the iFrame support to document explicitly.

**Comment by kairusds** [comment]
> I added the `CSP` environment variable in 0.5.0 to allow doing this directly.
> 
> You should be able to do something like `CSP="frame-ancestors https://example.com"`.
> 
> Let me know if you have any questions.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

just a question, but how do i add multiple csp directives to the env variable? if i add multiple of them, separated by a `;` it just won't load the hub for me

**Comment by uaoao** [comment]
Separate multiple urls with spaces.

**Comment by kairusds** [comment]
> Separate multiple urls with spaces.

no, i meant chaining the directives inside of the environment variable, since doing something like `"CSP=default-src: 'self'; font-src: 'self'; img-src: 'self;"` doesn't work and will just give me a configuration error on docker
