### ISSUE TITLE
Average line on graphs

### ISSUE THREAD

**Issue by ghost** [henrygd/beszel#117]
It would be great if we could add an average line on the graphs for the metrics such as CPU usage etc.

This would allow us to get a better understanding of our system performance over longer periods of time.

**Comment by alexzaitsev** [comment]
Isn't it already implemented? I see dropdown with "Average" as default.
<img width="1391" alt="Screenshot 2024-10-29 at 11 01 17" src="https://github.com/user-attachments/assets/64363d79-1e96-435d-bb69-2ddc74145174">

**Comment by henrygd** [comment]
Thanks for reminding me about this.

I think this person wanted a single trend line with less variability, but I think the current implementation is fine so I will close this issue.
