### ISSUE TITLE
Downtime/Alert Trigger History

### ISSUE THREAD

**Issue by ghost** [henrygd/beszel#122]
It would be nice if we could get a log style page where we can view previous alerts that have been trigged or previous downtimes. This is often helpful in comparing downtimes with patterns or server logs if they happen frequently.

**Comment by henrygd** [comment]
Sent alerts are logged on the the PocketBase logs page. Search for "Sent alert".

The time that systems go down is also logged on the logs page, and as of 0.2.0 you can reference gaps in charts to see roughly when systems were down or up.

For now I think this is sufficient, but if anyone has further input I'd be glad to hear it.
