### ISSUE TITLE
DOCKER_HOST with docker-socket-proxy

### ISSUE THREAD

**Issue by robflate** [henrygd/beszel#126]
I'm running Beszel in Docker. Everything works if I mount the docker socket but if I use a socket proxy and add `DOCKER_HOST: tcp://socket-proxy:2375` the agent reports the error;

`Closing idle connections. Error: Get "[http://localhost/containers/json":](http://localhost/containers/json%22:) dial tcp: lookup socket-proxy on 127.0.0.53:53: server misbehaving`

Could this be because the hub is on a separate network so it can't communicate via docker container names like `socket-proxy:2375`. If I use the containers IP it works `192.168.91.254:2375`.

Is this the intended behaviour or am I doing something wrong?

Here's my compose;

```
services:   
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    restart: unless-stopped
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "2183:8090"
    volumes:
      - /appdata/beszel:/beszel_data
    extra_hosts:
      - host.docker.internal:host-gateway

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      KEY: "xxxxxxxxxxxxxx"
      FILESYSTEM: /dev/sda3
      DOCKER_HOST: tcp://socket-proxy:2375 # NOT WORKING
      # DOCKER_HOST: tcp://192.168.91.254:2375 # WORKING

  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    restart: always
    networks:
      socket_proxy:
        ipv4_address: 192.168.91.254
    ports:
      - "127.0.0.1:2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
```

**Comment by henrygd** [comment]
> Could this be because the hub is on a separate network so it can't communicate via docker container names like socket-proxy:2375. If I use the containers IP it works 192.168.91.254:2375.

That appears to be the case. I don't think docker containers can resolve other containers by name unless they're in the same network. And the agent is in host network mode, so it's not in the same network as your proxy despite being in the same compose file.

Using the IP address looks like a good workaround though.

**Comment by henrygd** [comment]
Closing this issue, but let me know if you have any other questions.
