### ISSUE TITLE
reset password via console not working

### ISSUE THREAD

**Issue by xavier-hernandez** [henrygd/beszel#127]
Using unraid...

repo: henrygd/beszel:latest

Trying to go to the console to reset my password is not working.

:~# docker exec -it beszel bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown

:~# docker exec -it beszel sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown

**Comment by bengt-a** [comment]
beszel admin doesn't exist!
How can I reset my password?

```
bengt@ubuntu22[192.168.1.52]:~$ docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel admin update [email] [password]
Error: unknown command "admin" for "beszel"
Run 'beszel --help' for usage.
bengt@ubuntu22[192.168.1.52]:~$ docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel --help
Usage:
  beszel [command]

Available Commands:
  migrate     Executes app DB migration scripts
  serve       Starts the web server (default to 127.0.0.1:8090 if no domain is specified)
  superuser   Manage superusers
  update      Update beszel to the latest version

Flags:
      --dev                    enable dev mode, aka. printing logs and sql statements to the console
      --dir string             the PocketBase data directory (default "beszel_data")
      --encryptionEnv string   the env variable whose value of 32 characters will be used
                               as encryption key for the app settings (default none)
  -h, --help                   help for beszel
      --queryTimeout int       the default SELECT queries timeout in seconds (default 30)
  -v, --version                version for beszel

Use "beszel [command] --help" for more information about a command.
bengt@ubuntu22[192.168.1.52]:~$ docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel update
beszel 0.9.1
Checking for updates...
Latest version: 0.9.1
You are up to date
```

**Comment by kaidonato** [comment]
@bengt-a the available commands are showing you exactly what to do. The command is not admin it is superuser...

`docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel superuser update [email] [password]`

or

`docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel superuser create [email] [password]`

**Comment by bengt-a** [comment]
> [@bengt-a](https://github.com/bengt-a) the available commands are showing you exactly what to do. The command is not admin it is superuser...
> 
> `docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel superuser update [email] [password]`
> 
> or
> 
> `docker run --rm -v ./beszel_data:/beszel_data henrygd/beszel superuser create [email] [password]`

Thank you! Superuser worked like a charm!

**Comment by bengt-a** [comment]
I have to change my response on that. The command says that it was successful. But I still can't log in with the new password :(

**Comment by henrygd** [comment]
@bengt-a It should reset the password of your superuser account to log in to the PocketBase backend at `<your-url>/_/`.

Once you are in PocketBase you can change all user passwords for Beszel in the users table.

Let me know if this doesn't work for you.

**Comment by bengt-a** [comment]
I can change the password for the PocketBase login, but logging in at Beszel still doesn't work

**Comment by henrygd** [comment]
@bengt-a If you can access PocketBase then you can change any Beszel user's password.

In the sidebar go to Collections -> Users and then click on the user you want to modify.

An editor interface should slide in from the right and there will be a "Change password" toggle. Enter your new password and click "Save changes."

You should be able to log into Beszel with the new password.
