### ISSUE TITLE
Docker CPU and Memory usage display 0%

### ISSUE THREAD

**Issue by version-au** [henrygd/beszel#130]
![ssdocker](https://github.com/user-attachments/assets/3fc97680-265e-466c-90a1-34d0d46025f5)

I'm running this within Proxmox on a LXC container.
The container is running debian 12 with docker etc installed. 
It can see which containers are running but can't output their individual cpu and memory usage.

I suspect this is a limitation because of this setup as running a beszel docker agent on the proxmox host allows me to see the docker cotainers running and also their individual cpu and memory usage.

Am i doing something wrong? 
Love the software btw. ;)

**Comment by ajdaniel** [comment]
I have the same issue, since updating to the latest, my docker usage dropped to nothing. I already had an issue showing memory usage before (as you can see in the screenshot)

<img width="691" alt="image" src="https://github.com/user-attachments/assets/f8160b6a-2c23-4ddb-ba65-4eb73aaf0e0f">

**Comment by ajdaniel** [comment]
Also to confirm, my version of docker is `Docker version 27.1.2, build d01f264`

**Comment by ajdaniel** [comment]
Okay so I did more digging and I found out that my docker couldn't access memory information but I followed this guide (https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/) and it all works fine for me now. Might work for other people, particularly running on raspberry pis Like I am

**Comment by henrygd** [comment]
@ajdaniel Thanks, this has come up a few times in other issues so I'll make a note to add this info to the readme.

@version-au Try running `docker stats --no-stream` from within the lxc container. If it shows zero values there, then it's not something I can fix on this end.

I found this discussion on the proxmox forum, but the conclusion is to not run docker in an lxc container because weird things happen: https://forum.proxmox.com/threads/docker-stats-returns-zero-inside-lxc.115095/

**Comment by henrygd** [comment]
@version-au Were you able to figure this out? If not please check if you get any CPU / mem stats when running `docker stats --no-stream`.

**Comment by version-au** [comment]
> @version-au Were you able to figure this out? If not please check if you get any CPU / mem stats when running `docker stats --no-stream`.

Sorry been away for a few days. Running docker stats --no-stream shows 0% for usage and 0 for memory usage as well. I haven't had a chance to try anything from the link ajdaniel posted. 

I know running docker in an LXC is not supported or recommended but for my use case it's been great. If i find a work around or get any further with it i will post my results.

Cheers for your suggestions and time.

**Comment by henrygd** [comment]
@version-au  I'm closing this issue because it's not something I can fix on this end, but please let me know if you figure it out.
