### ISSUE TITLE
Discord notification support

### ISSUE THREAD

**Issue by steveiliop56** [henrygd/beszel#136]
I really love this project and its now a core part of my homelab, there is just one small thing missing. Discord. It would be awesome to have discord notifications alongside SMTP, I don't know how easy it will be to implement (due to pocketbase as the backend) but if it gets implemented it will be just awesome!

**Comment by no8ody** [comment]
There is already an open issue for the support of further notification options, see #71

**Comment by steveiliop56** [comment]
Oh alright closing this.
