### ISSUE TITLE
Command pallet blurry

### ISSUE THREAD

**Issue by steveiliop56** [henrygd/beszel#137]
I just discovered the command pallet and when I opened it, it was quite blurry. Here is a screenshot:

![image](https://github.com/user-attachments/assets/fec58f27-057d-47ff-9401-92df5e61a939)

(if you zoom in you will see the difference in the icons, command pallet icons vs background icons)

Compared to the rest of the app which is crystal clear it is a bit uncomfortable to my eyes *me problem?*

**Comment by henrygd** [comment]
I think this is an inherent issue with css transforms. There always seems to be some browser / device / os combination where it loses sharpness. For me it looks fine.

There's a shadcn issue for this where people say removing a class related to border-radius fixes it. I don't understand why that would have anything to do with it, but I'll try it out.

https://github.com/shadcn-ui/ui/issues/711

**Comment by steveiliop56** [comment]
Alright feel free to tell me when you need beta testing

**Comment by henrygd** [comment]
If you still have your local instance, can you try removing the `rounded-md` class on this line? That's what people suggest in the thread I linked above.

https://github.com/henrygd/beszel/blob/68824935e95fe330ad76ef150534a894891942ac/beszel/site/src/components/ui/command.tsx#L16

**Comment by steveiliop56** [comment]
> If you still have your local instance

Of course I have it, it's monitoring my entire homelab lol.

Yes man it solved it (and luckily it didn't lose the rounded corners)! You can safely remove it from your codebase and it should be good.

**Comment by henrygd** [comment]
Great, thanks.
