### ISSUE TITLE
[Feature Requests] Colored Tags or BG Colors for the rows

### ISSUE THREAD

**Issue by SonGokussj4** [henrygd/beszel#139]
Would it be possible to select the menu of each instance and assign a color so I can see at first glance instances that are interesting/problematic for me?

Something like this :-) Just an edited screenshot.
![image](https://github.com/user-attachments/assets/380faa35-1ed6-48c2-b6c2-289f6d7b28c8)

**Comment by henrygd** [comment]
Tags are planned. See #87.
