### ISSUE TITLE
 Error getting container stats: container_name - invalid data

### ISSUE THREAD

**Issue by Malek-GHub** [henrygd/beszel#144]
Hello

I've installed the Beszel Hub and Agent on a raspberry pi 4, with the logging Container Dozzle
The Hub can see the raspberry Pi cpu, disk and memory etc, 

![image](https://github.com/user-attachments/assets/37af5e6e-f6dc-4846-b070-6675a866f189)

however,  I cannot see any container information and am getting the following error in the logs of the Beszel agent

```
beszel-agent logs

 2024/09/01 15:40:59 Found network interface: eth0 (5065362491 recv, 1064108764 sent)
2024/09/01 15:40:59 Starting SSH server on :45876
2024/09/01 15:41:03 Error getting container stats: beszel - invalid data
2024/09/01 15:41:03 Error getting container stats: beszel-agent - invalid data
2024/09/01 15:41:03 Error getting container stats: dozzle - invalid data
2024/09/01 15:41:56 Error getting container stats: beszel-agent - invalid data
2024/09/01 15:41:56 Error getting container stats: beszel - invalid data
2024/09/01 15:41:56 Error getting container stats: dozzle - invalid data
2024/09/01 15:42:56 Error getting container stats: beszel - invalid data
2024/09/01 15:42:56 Error getting container stats: beszel-agent - invalid data
```

This is my docker compose , and env file.   I know this is insecure but I just wanted it to work like this first before installing the socketproxy... 
Any Ideas would be greatly appreciated..

```
docker-compose.yaml

services:  
   beszel:
     image: henrygd/beszel
     container_name: beszel
     restart: unless-stopped  
     env_file:
       - malmeser.env     
     ports:
       - '8090:8090'
     volumes:
       - ./volumes/beszel/config:/beszel_data

   beszel-agent:
     image: "henrygd/beszel-agent"
     container_name: "beszel-agent"
     restart: unless-stopped
     network_mode: host
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
     environment:
       PORT: 45876
       KEY: "ssh_key_here"
       FILESYSTEM: /dev/mmcblk02 # set to the correct filesystem for disk I/O stats

   dozzle: # Dozzle - Real-time Docker Log Viewer
     image: amir20/dozzle:latest
     container_name: dozzle
     restart: unless-stopped
     env_file:
       - malmeser.env
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only       
     ports:
       - 7070:8080
```

```
malmeser.env

# Common variables
PUID=1000
PGID=1000
TZ=Europe/Madrid


#Dozzle Specific variables
DOZZLE_LEVEL=info
DOZZLE_FILTER="status=running"
DOZZLE_HOSTNAME=Malmeser
DOZZLE_ENABLE_ACTIONS=true
#DOZZLE_REMOTE_HOST=  #add comma for more hosts
#DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label      

```

**Comment by henrygd** [comment]
Hi, you probably need to enable cgroups memory accounting.

It's an easy fix. See this article:

https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/

I'll add this info to the readme next time I update it.

**Comment by Malek-GHub** [comment]
That was it! 
I'm now getting docker cpu readings from the individual containers and no log errors anymore! 
![image](https://github.com/user-attachments/assets/41773227-cc1f-4033-9b4a-f5f391739741)

Thank you for the help!!

**Comment by henrygd** [comment]
No problem!

**Comment by lephtHanded** [comment]
thanks, just found this.

**Comment by ardenyang** [comment]
I got same error in my Synology DS918+ DSM 6.2，how to solve it on Synology ? Thanks.

Error log:
2024/11/16 23:26:22 ERROR Error getting container stats err="xxxx - no memory stats - see https://github.com/henrygd/beszel/issues/144"

**Comment by henrygd** [comment]
@ardenyang Please run `docker stats` on your device. Does it show your containers using 0 memory? If so, follow this guide to enable cgroups memory accounting:

https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/

**Comment by ardenyang** [comment]
> @ardenyang Please run `docker stats` on your device. Does it show your containers using 0 memory? If so, follow this guide to enable cgroups memory accounting:请在您的设备上运行 `docker stats`。它是否显示您的容器使用 0 内存？如果是这样，请按照本指南启用 cgroups 内存核算：
> 
> https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/

Thanks a lot.

**Comment by xinmans** [comment]
> Hi, you probably need to enable cgroups memory accounting.
> 
> It's an easy fix. See this article:
> 
> https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/
> 
> I'll add this info to the readme next time I update it.

if i use alpine on arm cpu，how set？

**Comment by henrygd** [comment]
@xinmans Looks like a bug in Alpine / OpenRC. I will try to help in the issue you created (#351).

**Comment by jauwshi** [comment]
> Hi, you probably need to enable cgroups memory accounting.
> 
> It's an easy fix. See this article:
> 
> https://akashrajpurohit.com/blog/resolving-missing-memory-stats-in-docker-stats-on-raspberry-pi/
> 
> I'll add this info to the readme next time I update it.

Even works on podman although the cgroup params were set. 
Checked with:
```
podman info | grep -i cgroup
```
Thanks!

**Comment by henrygd** [comment]
@emigrating Please [open a support discussion](https://github.com/henrygd/beszel/discussions/new?category=support) with the full error message and basic details of your setup, thanks.

**Comment by vk2r** [comment]
And in Proxmox ?
