### ISSUE TITLE
[Feature Request]  SSH agent

### ISSUE THREAD

**Issue by speedrapide10** [henrygd/beszel#147]
Hello,

Could you please add feature to add agent just by ssh connection. (Example Proxmox host since it's not recommended to install docker)
Please let me know if any additional information is needed.

Thank you,

**Comment by henrygd** [comment]
I'm not sure I understand what you mean.

You can use the binary if you don't want to install Docker. We have a [setup script here](https://github.com/henrygd/beszel/blob/main/supplemental/guides/systemd.md) which will install it as a system service on Linux.

**Comment by speedrapide10** [comment]
Yes i know that installing docker on top pro proxmox is possible since it's based on debian is possible but it's not recommended.
The request is to use only built in system feature like ssh/crontab for hosts that do not support docker agent.
![image](https://github.com/user-attachments/assets/d0f696ba-e619-487a-af1d-3c64e35b7503)

I hope you can get my idea

**Comment by henrygd** [comment]
The binary is just an executable file. It doesn't use Docker at all. Just ignore that button.

See this part of the readme: https://github.com/henrygd/beszel/blob/main/readme.md#binary

I recommend using the [install script](https://github.com/henrygd/beszel/blob/main/supplemental/guides/systemd.md) to make setup easier.

Download agent install script:

```bash
curl -sL https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh -o install-agent.sh && chmod +x install-agent.sh
```

Install agent:

```bash
./install-agent.sh
```

Update agent:

```bash
sudo /opt/beszel-agent/beszel-agent update && sudo systemctl restart beszel-agent
```

**Comment by speedrapide10** [comment]
Cool, thank you for the clarification. I confirm that it's working 👌
