### ISSUE TITLE
[Feature Request] Monitor Power usage

### ISSUE THREAD

**Issue by speedrapide10** [henrygd/beszel#148]
Hello,

Could you please add feature to monitor linux host power consumption in W (watts) ?
Please let me know if any additional information is needed.

Thank you,

**Comment by henrygd** [comment]
While it would be a great feature, I don't think there's a standardized way to monitor power consumption on systems that don't use a battery. Let me know if I'm wrong.

An alternative would be to use smart plugs and monitor the energy use of the plugs with Home Assistant.

If anything related to this is ever added upstream in [gopsutil](https://github.com/shirou/gopsutil), I'll be happy to add it here as well.

**Comment by speedrapide10** [comment]
Thank you for your feedback 👌
