### ISSUE TITLE
Email alert error

### ISSUE THREAD

**Issue by bitdoze** [henrygd/beszel#149]
Hello,

Using the docker image, the test email works but the app is giving :

failed to locate a sendmail executable path

When trying to send email

**Comment by henrygd** [comment]
Thanks, I wonder if this could be due to caching the mail client.

Has the container restarted after you updated SMTP settings? If not, please restart it.

If it's a caching problem then it should be an easy fix.

**Comment by henrygd** [comment]
Should work if you restart your container. Just committed a fix for future releases.
