### ISSUE TITLE
Bandwidth Recording - Bug

### ISSUE THREAD

**Issue by Mark-2445** [henrygd/beszel#150]
Hi, 

I've recently configured Beszel on a Raspberry Pi to monitor my other servers, I'm getting some werid behaviour on the network graphs:

![image](https://github.com/user-attachments/assets/633eebe0-9326-4d0f-b525-0322ecf02c6d)

**Comment by henrygd** [comment]
This is probably an edge case when initializing the stats. Can you please check the agent logs and paste any line that mentions a network interface on startup?

Thanks

**Comment by Mark-2445** [comment]
Hi, here are the start up logs:

2024/09/02 18:12:57 Found network interface: eth0 (696519166823 recv, 700036170059 sent)
2024/09/02 18:12:57 Starting SSH server on :45876

**Comment by henrygd** [comment]
Thank you. Did this happen right after you started or restarted the agent? Or had it been running for a while?

**Comment by Mark-2445** [comment]
It had been running for around 40 minutes before that happened, I will keep monitoring it to see if it happens again.

It's also showing on the 12 hour graphs, I'll keep you updated.

**Comment by henrygd** [comment]
Longer records are made by averaging the 1 minute record values, so that single record will probably mess up the y axis on every time period until it ages out.

I'd recommend deleting any records that have the bad values, or just delete and recreate the system if it's fairly new.

**Comment by Mark-2445** [comment]
Thanks, I've deleted the offending records and all appears normal now. 

Thanks for the help

**Comment by henrygd** [comment]
I still don't know exactly what caused this, but I refactored the network related code and added some basic handling in 0.3.0 to detect if the value is obviously too large. 

If it is, network stats are reinitialized. It will also log `Warning: network sent/recv is x/x MB/s. Resetting stats.`, along with the detected interface stats.

I'll close this issue so it's not hanging around forever, but if some gets the log above, please reply here or open a new issue.
