### ISSUE TITLE
Update systemd.md - add EXTRA_FILESYSTEMS

### ISSUE THREAD

**Issue by scriptzteam** [henrygd/beszel#159]
Hi, you should also update now systemd.md to reflect EXTRA_FILESYSTEMS

https://github.com/henrygd/beszel/blob/d2284c3fed0fa48f1b8f97902cc963f05812e098/supplemental/guides/systemd.md?plain=1#L113

`Environment="EXTRA_FILESYSTEMS=sdb"`

Thanks also for super cool piece of art :)

**Comment by henrygd** [comment]
No problem. Added commented out examples to the guide and script.

Also added a note about how to update the unit files.
