### ISSUE TITLE
[Feature Request] "push" style server monitoring

### ISSUE THREAD

**Issue by wy580477** [henrygd/beszel#16]
Thx for nice project.

Some of my servers don't have public routable address, and on servers with have public ip it's tiresome to config firewall on each one.

It would be nice if hub can listen on a http port and receive "push" from agent.

**Comment by henrygd** [comment]
This is on the radar for the future but not something I'm jumping into immediately.

The setup I think would have you specify user / pass on the agent then send data using the REST API. Password auth would need to be enabled.

For those having trouble with the current setup, it may be possible to connect using services like Cloudflare tunnel, WireGuard, or Tailscale.

**Comment by wy580477** [comment]
> The setup I think would have you specify user / pass on the agent then send data using the REST API. Password auth would need to be enabled.

Maybe different token for each client instead of user/pass will be more secure.

**Comment by henrygd** [comment]
Someone started a discussion on this, so I'm going to move conversation on this topic over there.

See #51
