### ISSUE TITLE
Feature Request: Ability to change default graph timeline view

### ISSUE THREAD

**Issue by Mark-2445** [henrygd/beszel#161]
When you click on a host, the current default is to show the past hour view. Could we allow this to be customised to a different timeline globally?

I find my self repeating a lot of clicks as I prefer looking at the 24 hour view myself, however this would be a personal preference of the user. 

The ability to choose 1h, 12h, 24h, 1w or 30d would be perfect.

**Comment by henrygd** [comment]
I'm adding a settings page in the next release so I'll try to get this option on there.

**Comment by henrygd** [comment]
Added in 0.4.0. Check the settings page and let me know if you have any trouble with it.
