### ISSUE TITLE
Feature Request: Show servers hostname in server info

### ISSUE THREAD

**Issue by Mark-2445** [henrygd/beszel#162]
Hi, 

On my install I have all my servers setup with their friendly names, it would be useful if we could show the systems hostname as taken from the machine its self in the server info section.

![image](https://github.com/user-attachments/assets/b3a1f652-1828-42c2-96ab-4847fd349293)

**Comment by henrygd** [comment]
Added in 0.4.0. Hostname will be displayed if it's different than the system name or user specified IP / host.

Let me know if you don't see it.
