### ISSUE TITLE
Run as rootless

### ISSUE THREAD

**Issue by SonGokussj4** [henrygd/beszel#169]
Hello, I'm trying to run beszel-agent as rootless docker. Is that possible?

```sh
$ docker context ls
NAME         DESCRIPTION                               DOCKER ENDPOINT                     ERROR
default      Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
rootless *   Rootless mode                             unix:///run/user/1001/docker.sock

$ cat docker-compose.yaml
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    privileged: true  # <-- Not sure if this does anything
    network_mode: host
    volumes:
      - /run/user/1001/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3N......OpvRdFLD6p"

$ docker compose up -d

$ docker ps
CONTAINER ID   IMAGE                 COMMAND   CREATED         STATUS          PORTS   NAMES
6c76b9f0b748   henrygd/beszel-agent  "/agent"  12 minutes ago  Up 12 minutes           beszel-agent
```

Beszel-agent logs when started (any chance to inscrease logs to debug or something?)
```sh
2024/09/17 13:12:08 Detected root fs: sdb2
2024/09/17 13:12:08 Detected network interface: tap0 (3221054 recv, 67199 sent)
2024/09/17 13:12:08 Starting SSH server on :45876
```

The added client is showing red dot but there are no logs so I don't know what is happening.

Additional info, if I run `telnet` from host machine running the beszel web UI:

```sh
# Client1 running as default root docker
$ telnet 192.168.89.61 45876
Trying 192.168.89.61...
Connected to 192.168.89.61.
Escape character is '^]'.
SSH-2.0-Go

# Client2 running as rootless docker
$ telnet 192.168.89.62 45876
Trying 192.168.89.62...
telnet: Unable to connect to remote host: Connection refused
```

Why am I in need of this. I'm running my services as rootless docker and if I run beszel-agent as root, I don't see any of my rootless services.

Am I missing something of do I have something badly configured?

**Comment by henrygd** [comment]
If you need to change the endpoint, you should be able to do that by setting the `DOCKER_HOST` environment variable to `unix:///run/user/1001/docker.sock`.

If it's showing red, then it's probably some other issue with the connection. Try checking the logs page in PocketBase to see if it has anything related.

**Comment by henrygd** [comment]
Actually I think I read that wrong. Seems like it might be an issue with the port not being exposed.

Try manually exposing the port in the compose file. Maybe there's something with host network mode in rootless where it doesn't automatically expose the port.

**Comment by SonGokussj4** [comment]
Hell yeah! **Thanks a bunch**! 

My changes for future references:
```
$ cat docker-compose.yaml
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    #network_mode: host  # <-- commented out
    volumes:
      - /run/user/1001/docker.sock:/var/run/docker.sock:ro
    ports:
      - "45876:45876"  # <-- added
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfTKz5Uw+IZo+rulOEbgGl2ngz9e8adrfOpvRdFLD6p"
```

**Comment by henrygd** [comment]
Awesome, but check the logs to see if it's still detecting your network interface.

Generally you need host network mode to be able to find it.

If it doesn't find the interface, try both `network_mode: host` and also manually exposing the ports.
