### ISSUE TITLE
Docker swarm agent deployment leads to drop in all metrics

### ISSUE THREAD

**Issue by suranyami** [henrygd/beszel#17]
Hi. Love this project! Well done! I've been looking for something like this to replace Netdata.

I tried it out on a single node, and all went well and could see that metrics roughly matched what I was seeing in HTOP and Swarmpit.

Then added a node to the docker swarm, and went through the service addition and adding the `docker-compose.yml` section to my original `docker-compose`, adding `deployment mode: global` to the agent like this:

```docker-compose
version: '3.3'
services:
  beszel:
    image: henrygd/beszel:latest
    ports:
     - 8090:8090
    volumes:
     - /mnt/data/beszel_data:/beszel_data
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.hostname==nano
  
  beszel-agent:
    image: henrygd/beszel-agent:latest
    environment:
      FILESYSTEM: /dev/nvme0n1p1
      KEY: ssh-ed25519 *KEY OBSCURED FOR SECURITY*
      PORT: '45876'
    ports:
     - 45876:45876
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global

networks:
  default:
    driver: overlay
```

This is a snapshot of the docker memory usage… you can see that after I added the other agent, the Minecraft server that's still running on that machine and using about 7GB RAM, drops down to 0.

<img width="569" alt="Screenshot 2024-07-26 at 10 56 01" src="https://github.com/user-attachments/assets/d78ef36c-90bc-4e75-bb5e-f72c6e188e3c">

What's going on here?

Should there be a different SSH key for each node?

Also, I was unable to get the agents to work at all without adding this:

```yaml
    ports:
     - 45876:45876
```

**Comment by henrygd** [comment]
The agents all use the same public key so that shouldn't be the problem.

Are the nodes red or green?

From the screenshot it looks like they're connected and returning the container names with all values as zero. Is that right? And you have only one agent running per system?

What about other system metrics outside of docker?

I'm definitely not an expert on swarm, but it would be nice to figure this out because it does seem like a convenient way to deploy the agents.

**Comment by suranyami** [comment]
Okay, figured out a couple of things…

The fact that each of the nodes were on the same port (and replicated),  I think  it may have been grabbing whichever node responded first. That leads to weird things like one node showing metrics for docker containers running on a different machine.

Wouldn't it be simpler for the agents to connect back to the hub? Either by API, or with a special SSH port (like the agents currently have)?

The workaround I have for the moment is to *not* use `global` deploy mode, and specify the same service block individually for each node, then assign a different SSH port for each node. e.g.:

```docker-compose
  beszel-agent-nano:
    image: henrygd/beszel-agent:latest
    environment:
      FILESYSTEM: /dev/nvme0n1p1
      KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPaeg+GJnJByGCq/3H5V0n/Rw/DAkpTWAV2VX9nj1e9O
      PORT: '45876'
    ports:
     - 45876:45876
# ...
      placement:
        constraints:
         - node.hostname==nano

  beszel-agent-pico:
    image: henrygd/beszel-agent:latest
    environment:
      FILESYSTEM: /dev/mmcblk2p1
      KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPaeg+GJnJByGCq/3H5V0n/Rw/DAkpTWAV2VX9nj1e9O
      PORT: '45877'
    ports:
     - 45877:45877
# ...
      placement:
        constraints:
         - node.hostname==pico
```

The only problem with this approach is it would soon become unwieldy for all the machines I want to monitor.

Each agent being able to "phone home" would seem like a better approach.

**Comment by suranyami** [comment]
Regarding monitoring outside of `beszel`, both `htop` and the Swarmpit dashboard show the correct memory, cpu, disk, etc. for each node.

<img width="847" alt="swampit-nodes" src="https://github.com/user-attachments/assets/897998a5-2594-444a-a25f-7285683b6d57">

<img width="1924" alt="swarmpit-dash" src="https://github.com/user-attachments/assets/b42812e5-97fa-44f5-81cf-831189b8ee55">

<img width="1293" alt="htop-nano" src="https://github.com/user-attachments/assets/80bfd795-ee79-4ca2-8ff2-5ae55de0ae0b">

<img width="970" alt="htop-pico" src="https://github.com/user-attachments/assets/3ec37828-44b5-4d84-b896-8d663e7bdf5b">

**Comment by suranyami** [comment]
So, I guess this isn't really a bug, but a limitation caused by using Docker Swarm.

Will close this issue, since it is possible to work around it.

**Comment by Stitch10925** [comment]
@suranyami 

I am running the same setup as you: Docker Swarm, Beszel Agent with global deployment, Swarmpit, etc. I don't have the same issue you have with the agents, so I'm wondering if you set it up correctly.

1. I noticed that you didn't use the host port for the agents
2. I'm wondering how you added the nodes in Beszel. Did you add them by using host names, IP addresses, ...?

What I think happened in your case, is that you were accessing the nodes via the swarm's ingress network, which has an internal load-balancer, which is probably why you were being routed around. You should add the nodes by their static IP address in Beszel.

**Comment by haythamelkhoja** [comment]
> Okay, figured out a couple of things…
> 
> The fact that each of the nodes were on the same port (and replicated), I think it may have been grabbing whichever node responded first. That leads to weird things like one node showing metrics for docker containers running on a different machine.
> 
> Wouldn't it be simpler for the agents to connect back to the hub? Either by API, or with a special SSH port (like the agents currently have)?
> 
> The workaround I have for the moment is to _not_ use `global` deploy mode, and specify the same service block individually for each node, then assign a different SSH port for each node. e.g.:
> 
> ```
>   beszel-agent-nano:
>     image: henrygd/beszel-agent:latest
>     environment:
>       FILESYSTEM: /dev/nvme0n1p1
>       KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPaeg+GJnJByGCq/3H5V0n/Rw/DAkpTWAV2VX9nj1e9O
>       PORT: '45876'
>     ports:
>      - 45876:45876
> # ...
>       placement:
>         constraints:
>          - node.hostname==nano
> 
>   beszel-agent-pico:
>     image: henrygd/beszel-agent:latest
>     environment:
>       FILESYSTEM: /dev/mmcblk2p1
>       KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPaeg+GJnJByGCq/3H5V0n/Rw/DAkpTWAV2VX9nj1e9O
>       PORT: '45877'
>     ports:
>      - 45877:45877
> # ...
>       placement:
>         constraints:
>          - node.hostname==pico
> ```
> 
> The only problem with this approach is it would soon become unwieldy for all the machines I want to monitor.
> 
> Each agent being able to "phone home" would seem like a better approach. It would also mean that there is no need to even configure agents in beszel… they would auto-announce themselves.

I did the same thing ... works like a charm, thanks.

**Comment by suranyami** [comment]
> @suranyami
> What I think happened in your case, is that you were accessing the nodes via the swarm's ingress network, which has an internal load-balancer, which is probably why you were being routed around. You should add the nodes by their static IP address in Beszel.

Interesting. I'll take another look at my setup.

Actually, now that I think about it, I originally set this swarm up using Portainer, then migrated to Swarmpit, so that may be the reason for the odd configuration. Probably best I recreate the swarm from Swarmpit from scratch, then.

Totally off-topic, I know, but kinda good to know for monitoring.

Thanks for the advice!

Sorry I only just got around to reading this. It popped up in my email notifications just now for some reason.
