### ISSUE TITLE
How to rename disks and remove dashboard panels

### ISSUE THREAD

**Issue by jerdzho** [henrygd/beszel#174]
Is it possible to rename this?
![disk](https://github.com/user-attachments/assets/aa04f80e-e32a-48ac-ad01-ebbd8d523de1)

Is it possible to remove dashboard panel like this for example?
![panel](https://github.com/user-attachments/assets/90df8831-9569-4613-baa3-0b85368ca8e9)

**Comment by henrygd** [comment]
No way to change the name of the partitions currently. It's just uses the actual partition name on the system.

The swap chart only shows if you have swap space allocated, but I'll change it in the next release to only show if you have swap actually in use.
