### ISSUE TITLE
[Unraid] Cannot get EXTRA_FILESYSTEMS to detect other drives

### ISSUE THREAD

**Issue by DinoHorvat96** [henrygd/beszel#181]
Hi,
To preface this, Beszel works great on my Unraid system, except for one thing - Extra filesystems. I know the developer of this project is not too familiar with Unraid, but hopefully I can still find a solution to this issue.
I can only see the filesystem where Beszel is installed onto (which is one of my NVMe drives), but I simply cannot get the other drives to show up - the logs keep saying that it cannot find the mounting point no matter what I configure.

This is my current configuration (which unfortunately still does not work):
![image](https://github.com/user-attachments/assets/93e24698-6318-4f7e-a6ea-b854eb326179)

This configuration culminates into these logs:
![image](https://github.com/user-attachments/assets/3550fd4d-5bcf-4ba9-aafe-1fab600970a1)

Which allows me only to see the graph of the drive where Beszel is installed:
![image](https://github.com/user-attachments/assets/bdc5c1bc-eb29-4df7-9ea9-67c18f6f6dcf)

This is my `df -h` output:
![image](https://github.com/user-attachments/assets/e6a193b8-064f-4a34-907f-7dc4790ecd5f)

This is the `lsblk` output:
![image](https://github.com/user-attachments/assets/5772f93a-cef7-487f-8ecb-58fc5b7bac0c)

And finally, the `sudo fdisk -l` output:
![image](https://github.com/user-attachments/assets/0f658444-2e86-413f-a088-22f217282f59)
![image](https://github.com/user-attachments/assets/79c2309a-02d0-4cf6-b284-69197b8d7d53)

As can be seen, Beszel is installed on `nvme1n1p1`, AKA `cache_files`.
I want to add `md1p1` (or `disk1`, a HDD) and `nvme0n1p1` (or `vms_nvme`, another NVMe drive) to the list so I can track their usage as well.

I am obviously configuring something incorrectly, but I've tried so many variations of different device names and different mounting points that none of them has worked and I am lost as to what I am missing.
Sidenote: I haven't changed the `FILESYSTEM` variable from it's default value of `/`, unsure if that would be contributing to the cause of the issue.
Any help would be greatly appreciated, thank you.

**Comment by henrygd** [comment]
Is this using docker? If so, remove the `EXTRA_FILESYSTEMS` env var. It should automatically pick up devices in /extra-filesystems without that.

What does your root usage chart look like? It says it's picking up loop2 and looks like `nvme1n1p1` is being added as an extra.

Assuming you're on the latest version, try passing a bad value for `FILESYSTEM`, i.e. `FILESYSTEM=/xyzzy`. It should then log every partition it finds, which can help debug.

**Comment by DinoHorvat96** [comment]
> Is this using docker? If so, remove the `EXTRA_FILESYSTEMS` env var. It should automatically pick up devices in /extra-filesystems without that.

It is. And removing `EXTRA_FILESYSTEMS` seems to have worked, I can now see the other drives. Thank you!
![image](https://github.com/user-attachments/assets/a8dc3ddd-d716-4570-87ea-429ef6994224)


> What does your root usage chart look like? It says it's picking up loop2 and looks like `nvme1n1p1` is being added as an extra.

Root usage looks like this:
![image](https://github.com/user-attachments/assets/fde7f805-0ecf-4cb5-b1a6-4db65fe270e5)
It seems that it picks up the docker image as the root.

> Assuming you're on the latest version, try passing a bad value for `FILESYSTEM`, i.e. `FILESYSTEM=/xyzzy`. It should then log every partition it finds, which can help debug.

This is everything it found:
![image](https://github.com/user-attachments/assets/e29c37db-6878-4d51-9953-c8a0a975c932)
It's picking up `loop2` via the `FILESYSTEM` value of `/` as that seems to be it's mounting point.
There is a docker socket variable which points to the docker:
![image](https://github.com/user-attachments/assets/3ec88858-44a5-4b29-82a6-1ec21968ae93)

**Comment by henrygd** [comment]
Perfect, is it all working properly now?

If you don't want loop2 as your root, you should be able to change it with `FILESYSTEM=nvme1n1p1`.

As far as the set up on Unraid, is this a template where it presents `EXTRA_FILESYSTEMS` to you as a valid option for Docker? If so I'll try to get that removed to reduce confusion.

**Comment by henrygd** [comment]
No problem!
