### ISSUE TITLE
[minor bug] Typo on disk i/o graph

### ISSUE THREAD

**Issue by yurividal** [henrygd/beszel#187]
The graph for external disk i/o shows "Throughput of of <drive name>"

![image](https://github.com/user-attachments/assets/fc4af7e4-26ab-4fc6-a64d-fe69a7618d07)

Issue is here: https://github.com/henrygd/beszel/blob/f350d61ee2a89a8e0761e7a23df6166d3f38cb92/beszel/site/src/components/routes/system.tsx#L447

**Comment by henrygd** [comment]
Thanks for pointing that out! Fixed it for the next release.
