### ISSUE TITLE
CPU usage should have a minimum time interval (and maybe memory too)

### ISSUE THREAD

**Issue by yurividal** [henrygd/beszel#191]
I have recently installed beszel. I set an alert on one of.my servers to alert me if CPU usage goes over 90%.
But, I keep getting alerts even on small CPU spikes, which are expected if a server is performing a quick intensive task.
Maybe, there should be an option to set a time delta.
Example: "if CPU usage is above 90% for more than 30 seconds, then alert"

This should make it easier to identify actual CPU hogue, and processes that might be stuck.

**Comment by henrygd** [comment]
The CPU alerts are currently based on average usage over the previous one minute, so 90% usage for only 30 seconds should not trigger an alert.

I'm planning to add the ability to customize the time period from 1min to 60min in a future update. There is an open issue tracking this here: #93
