### ISSUE TITLE
Docker stats issue

### ISSUE THREAD

**Issue by n-bilalis** [henrygd/beszel#194]
In the latest version `v0.5.0`, there is an issue with the Docker stats.

The graph in both the `CPU usage` and in the `Memory usage` appears "jagged". In the following image you can see the graph before and after the update to `v0.5.0`.

![image](https://github.com/user-attachments/assets/76426617-2632-44f6-9959-9bcc5b930520)

The problem seems to be that stats come back as `0` at intervals, so the graph line drops. Especially for the `Memory usage` that can't be true:

![image](https://github.com/user-attachments/assets/b5350705-e128-4214-8e9b-5d59803871ce)

If I choose `12 hours` the line smooths out a bit, but still it doesn't make sense to have that kind of variability.

**Comment by henrygd** [comment]
This is likely related to a bug in older versions of Docker.

What's your output of `docker version`?

Unless you're locked into an older version by your OS -- like Synology users -- I'd recommend updating to the latest version (27).

However, I did look into this a bit yesterday and should be able to add a workaround for old versions.

**Comment by henrygd** [comment]
Let me know if agent 0.5.1 fixes the issue.

**Comment by n-bilalis** [comment]
> Let me know if agent 0.5.1 fixes the issue.

Yes, it's fixed, thank you for your prompt response!

P.S. Unfortunately, I'm stuck at version 24.
