### ISSUE TITLE
Total Memory Usage is not the same as the actual.

### ISSUE THREAD

**Issue by timmyhbk** [henrygd/beszel#198]
**Describe**
There is a discrepancy between the memory shown in the Total Memory Usage graph and the actual memory usage. The graph is always lower than the actual.

I have encountered this problem on multiple machines (Ubuntu*5+Synology*1). It seems that only the agent with a binary installation on Proxmox is reporting the correct values. I had suspected that it was a docker agent issue, but when testing on an Ubuntu VM, both the docker and binary agents returned incorrect values.

**Synology NAS @ docker**
![ty](https://github.com/user-attachments/assets/38bbf265-ef8d-4542-bca9-7117a8f2876d)

**Ubuntu 24.04 @ docker**
![n100](https://github.com/user-attachments/assets/b1fee7ee-bea6-47ee-88f5-65fdb19ceb95)

**Proxmox 8.2.7 @ binary**
![pve](https://github.com/user-attachments/assets/a1c74f19-0138-446a-9dca-e50e2d5a1e4a)

**Version:** 0.5.1
**System:** Ubuntu 24.04 / Debian 12 (PVE) / Synology DSM 7.2.2

**Comment by henrygd** [comment]
It's not incorrect, it just uses a different calculation than htop.

My understanding is that there's no single right way to calculate used memory in Linux. You'll often see htop, top, free, btop, etc., with slightly different figures.

We use the `Used` value from gopsutil ([link](https://pkg.go.dev/github.com/shirou/gopsutil/v4@v4.24.6/mem#VirtualMemoryStat)), which on Linux is [Total - Free - Buffers - Cached](https://github.com/shirou/gopsutil/blob/2e10d9f7d0fbe5db80b5748c82f136b48e829233/mem/mem_linux.go#L307). It's also the default calculation used by Astra Monitor, which is what I compared it against while developing. The htop figure probably includes a greater share of memory which can still be reclaimed if necessary.

Maybe it would be best to align it with `free`, though I'm not sure what calculation that uses. I can also add an environment variable to let you choose a different formula.

For reference, use `cat /proc/meminfo` to see your current memory figures.

**Comment by timmyhbk** [comment]
This is the `cat /proc/meminfo` situation for 3 systems.
Thanks!

Synology NAS @ docker
![1215](https://github.com/user-attachments/assets/8df1b3c2-e5d0-4ac2-bc7e-1dfa7b39b752)

Ubuntu 24.04 @ docker
![n10](https://github.com/user-attachments/assets/f6917330-0fb3-430f-8ba6-4846214d7b2f)

Proxmox 8.2.7 @ binary
![pve](https://github.com/user-attachments/assets/b2b51bee-770c-4dfc-80bd-558cddf4f80d)

**Comment by henrygd** [comment]
I added the `MEM_CALC` env var in 0.5.2 to allow you to change the memory calculation.

No rush, but please try setting `MEM_CALC=htop` and let me know if the values become more aligned with what htop says.

**Comment by timmyhbk** [comment]
Yes, it works. Memory Usage for all machines is very close to htop now.

Thanks for your help!

**Comment by henrygd** [comment]
No problem. I'll close the issue, but let me know if you have any other questions.
