### ISSUE TITLE
Feature Request - Hardware temperature

### ISSUE THREAD

**Issue by ajdaniel** [henrygd/beszel#20]
I would like to monitor the CPU temperature of my system, and even other temps that could be found.

A quick search shows a CPU temp golang library which might be useful: barista.run/modules/cputemp

**Comment by henrygd** [comment]
Just released 0.2.0 which includes a temperature chart.

No notifications for sensor temps yet but someone can open an issue for that if they'd like.

If the temperature chart doesn't show, check that your system is able to access the sensors. On Linux, try the `sensors` command. You may not have access if your system hardware is virtualized.

**Comment by ajdaniel** [comment]
Amazing thanks!
