### ISSUE TITLE
Wrong temp on AMD Zen 3 processor. 

### ISSUE THREAD

**Issue by cichy1173** [henrygd/beszel#201]
Hello. I connected Beszel Agent with Beszel Hub. Server with Agent uses AMD Ryzen 7 5700G processor. I see that temperature is read in wrong way.

![image](https://github.com/user-attachments/assets/5657cdf7-2da8-4e01-8962-ed1d46c38fb2)
![image](https://github.com/user-attachments/assets/6fd3c113-8d22-49a9-96c6-1298b50adbab)

I checked `sensors` and I think the correct CPU temp is:

```shell
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +37.9°C
```
And the same temp shows:
```
TSI0_TEMP:              +37.9°C  
```
It shows the same temp as cpu temp sensor in Home Assistant. 

I checked this again and I see that Beszel sees the valid temperature.

![image](https://github.com/user-attachments/assets/4b649bb6-5705-4132-8b76-2f6e394672fd)

But also Beszel gets another temps that are not real, like:

```shell
TSI2_TEMP:             +3892314.0°C  
TSI3_TEMP:             +3892314.0°C  
TSI4_TEMP:             +3892314.0°C  
TSI5_TEMP:             +3892314.0°C  
TSI6_TEMP:             +3892314.0°C  
TSI7_TEMP:             +3892314.0°C  
```

I haven't checked your code, but I think agent just gets all temps from the `sensors` and AMD shows temperature in a little bit different way than Intel. I think it can be fixed in simple way by allowing user to define temperature sensor manually.

 Also I see that Beszel agent sends NVME drives temperature which would be pretty cool to show on second graph.

**Comment by henrygd** [comment]
Is it showing those huge values on the hour chart, or only on the longer charts?

As of 0.5.2, everything over 200 degrees should be automatically excluded.

You can whitelist sensors with the `SENSORS` env var. So do something like `SENSORS=k10temp_tctl,amdgpu_edge,nvme_sensor_8`

**Comment by cichy1173** [comment]
Changed how you said, I see that 40000 C metric isn't gathered, but I am waiting till tomorrow as graph get cleaned. 
Thanks for help!

**Comment by henrygd** [comment]
No problem!
