### ISSUE TITLE
Disk not showing

### ISSUE THREAD

**Issue by 9M2PJU** [henrygd/beszel#202]
[Unit]
Description=Beszel Agent Service
After=network.target

[Service]
Environment="PORT=45876"
Environment="KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUYSEJ9YcBmoalIPMTs7VohlIaaSZ4AWeGMEaTrZ8Ih"
Environment="EXTRA_FILESYSTEMS=vg_root-lv_data"
Environment="FILESYSTEM=sdb2"
ExecStart=/opt/beszel-agent/beszel-agent
User=beszel
Restart=always

[Install]
WantedBy=multi-user.target

native install.

EXTRA_FILESYSTEMS not showing on hub

**Comment by henrygd** [comment]
Did you figure this out?

If not, `LOG_LEVEL=debug` will log all the disks / partitions the agent can see.
