### ISSUE TITLE
[Feature Request] Get the host to be monitored from the environment variable

### ISSUE THREAD

**Issue by azhezzzz** [henrygd/beszel#206]
I like this project very much, thank you for your contribution ！
But when I want to add multiple monitoring hosts at a time, I need to operate on the web all the time, and it is also a bit troublesome when I want to control the hosts to be monitored programmatically.
Can add a dozzle-like processing method or other way to control the list of monitored hosts? Then I can easily add or delete multiple hosts.

dozzle-like:
https://dozzle.dev/guide/remote-hosts
`DOZZLE_REMOTE_HOST:=tcp://167.99.1.1:2376|foo.com,tcp://167.99.1.2:2376|bar.com`

**Comment by henrygd** [comment]
Yes, I do plan to add something for this at some point.

There's a related issue (#70) that proposes using a yaml configuration file.

I should be able to make it so the program reads a `config.yml` file in the data directory on startup and syncs the systems with what is defined in the file.

Would that work for you?

**Comment by azhezzzz** [comment]
Yes, it work for me
I just need a way that can easily control the list of monitored hosts.

**Comment by henrygd** [comment]
As of 0.6.2, systems can be managed in a `config.yml` file inside your data directory.

You can export your current systems by going to `/settings/config`.

Let me know if you run into any issues with this.
