### ISSUE TITLE
Microsoft Teams notifications not working

### ISSUE THREAD

**Issue by Denvek** [henrygd/beszel#207]
I've set up Beszel to monitor our servers, and I'm attempting to get the notifications set up to push to a Microsoft Teams webhook, but I'm not receiving the notification. I know that the notifications work, as I am able to successfully receive the email notifications, and also via a Discord webhook. I know that the webhook is set up in Teams correctly as it does receive notifications from other services as expected, but when I set it up in Beszel and click the Test URL button I get the message that the notification has been sent but I don't receive the notification in Teams.

I don't know if the issue itself is with Beszel or Shoutrrr, the only thing I can see is that in the Shoutrrr documentation about how to transate the webhook URL into the Shoutrrr format it gives the Teams webhook URL format as https://_organization_.webhook.office.com/webhookb2/_group_@_tenant_/IncomingWebhook/_altId_/_groupOwner_, and the URL I have has another segment after the groupOwner, although it doesn't work if I include or exclude that in the Shoutrrr URL.

**Comment by henrygd** [comment]
It could have something to do with Teams changing how webhooks work.

There are open issues about it in both the shoutrrr and watchtower repos:

https://github.com/containrrr/shoutrrr/issues/446

https://github.com/containrrr/watchtower/issues/1997

The latter has a workaround using an email address that posts to your channel.

If you want to test with shoutrrr directly, you can download the binary from their [releases page](https://github.com/containrrr/shoutrrr/releases/tag/v0.8.0) and use the CLI with the debug flag:

```bash
shoutrrr send -d \
    --url "<SERVICE_URL>" \
    --message "<MESSAGE BODY>"
```

I don't think there's anything we're doing on this end that would break it, but if the notification works when run directly with shoutrrr, let me know and I'll fix it from there.

**Comment by henrygd** [comment]
Thanks for the info, I'll point others here if they run into the same problem.

Closing the issue since it's not something I can fix on this side. If shoutrrr devs release a fix I'll make sure it's updated in Beszel.

**Comment by serverleader** [comment]
Hey guys, I fixed the shoutrrr issue with teams
I put a pull request in but no response ... 
@henrygd if you apply this https://github.com/containrrr/shoutrrr/pull/460/commits
to your next release teams notifications will work.

meanwhile if anyone wants a docker image with the teams fixed can get it by:
`docker pull serverleader/beszel-v0.10.2-teamsfix`

or meawhile you can change your docker-compose.yml to:
`services:
  beszel:
    image: serverleader/beszel-v0.10.2-teamsfix
    container_name: beszel`

**Comment by henrygd** [comment]
@serverleader Awesome, thanks!

I just forked Shoutrrr, so you can [make the same PR here](https://github.com/henrygd/shoutrrr) and I'll try to get it in the next release.

@beatkind has a popular Watchtower fork and just forked Shoutrrr. Maybe you should make a PR there as well: https://github.com/beatkind/shoutrrr

@nicholas-fedor also has an active fork here: https://github.com/nicholas-fedor/shoutrrr

Ideally we'll switch to one of those at some point.

**Comment by serverleader** [comment]
thanks @henrygd PR's done ;)
