### ISSUE TITLE
Can't show anyting on my iPhone

### ISSUE THREAD

**Issue by ardenyang** [henrygd/beszel#210]
This has a very good monitoring suite!  thank you!

I can login in x.x.x.x:8090 in my PC, However when I open same URL in my iPhone (iOS 16.2) Safari , It's show nothing (a blank page). I try to refresh page and same. I change to use Chrome / Firefox / Edge and all can't show correct login page. 
I use another iPhone (iOS 17.0), The URL show correct. 

beszel and beszel-agent all latest version. Is the current version incompatible with iOS 16.2? 
It's a pity that such a good tool can't be used on mobile phones, Let me know if there's any helpful information I can share. Thanks.

![11120241018102914](https://github.com/user-attachments/assets/a4e0a6d1-7f29-45ba-80f7-2c9584a8a720)

**Comment by ardenyang** [comment]
Thank you, I am looking forward next release.

**Comment by henrygd** [comment]
No problem. Should be fixed now in 0.6.1.

**Comment by ardenyang** [comment]
Upgrade to 0.6.1, confirm that issue solved.  Thank you.
