### ISSUE TITLE
Potential Regression with Beszel v0.6.0

### ISSUE THREAD

**Issue by arnabapp** [henrygd/beszel#212]
Hello

There seems to be a regression with between agent v0.6.0 and v0.5.3

![image](https://github.com/user-attachments/assets/ec43f0cb-c585-431f-8aa4-95fc928b7b16)

In Agent v0.5.3 i can see Docker CPU Usage and Memory Usage charts
![image](https://github.com/user-attachments/assets/e2e79c0b-8add-479a-bb2d-1eeeae6eddfe)

But in Agent v0.6.0 these charts are no longer visible
![image](https://github.com/user-attachments/assets/c26b16a7-2b75-4604-8a92-f5447ceb8736)

**Comment by henrygd** [comment]
Please run `docker version` and paste the output. I think you're on 24 or earlier, right?

**Comment by arnabapp** [comment]
Running Ubuntu 24.04 LTS with Docker 27.3 on both servers
```
arnab@Plex-Dev:~$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
=============
```
arnab@Plex-Prod:~$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by henrygd** [comment]
Interesting thanks. I switched things around slightly to help w/ older versions but not sure why anything would change if you're using 27.

Can you please try running the agent with `LOG_LEVEL=debug` and let me know what it says about docker?

It should log something like `Docker version=27.3.1 concurrency=5` or `Error getting docker stats`.

**Comment by arnabapp** [comment]
Hi

Managed to fix the issue after i enabled LOG_LEVEL: debug
Was getting this error 
```
2024/10/19 19:28:40 DEBUG Error getting docker stats err="Get \"[http://localhost/containers/json\":](http://localhost/containers/json/%22:) dial unix /var/run/docker.sock: connect: permission denied"
```
Removed the  ```user: ${PUID} ``` from docker compose file and its working as expected

Thanks a lot for your help

**Comment by henrygd** [comment]
No worries!

Another option is to run a [docker socket proxy](https://github.com/linuxserver/docker-socket-proxy) and specify it with the `DOCKER_HOST` env var.

That way you don't need to use the socket directly.
