### ISSUE TITLE
[FEATURE] Address for notifications

### ISSUE THREAD

**Issue by gander** [henrygd/beszel#220]
![Screenshot_20241024-171216.png](https://github.com/user-attachments/assets/45402da1-1aa1-4fda-ba4e-0979680c7aae)

Allow configure address when behind reverse proxy

**Comment by henrygd** [comment]
Changing the Application URL on `/_/#/settings` should update the links used in notifications.

Let me know if that doesn't work for you.

**Comment by gander** [comment]
yes it works. I don't know why I didn't find these settings earlier.

**Comment by canidam** [comment]
Wait, does this means I can update the app to be aware it's behind a reverse proxy? I tried to do that without success so far

**Comment by gander** [comment]
@canidam No, the app is not aware that it is behind a reverse proxy, but you can set its address so that notifications show the correct address.
