### ISSUE TITLE
Agent Crash: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Stitch10925** [henrygd/beszel#221]
I enabled debug mode on the agents to see why performance for me quite bad and noticed that the agent crashed on the following error:

`fatal error: fatal error: concurrent map writes
 concurrent map writes
 
 goroutine 362 [running]:
 beszel/internal/agent.(*dockerManager).getDockerStats(0xc00006a6e0)
 	/app/internal/agent/docker.go:60 +0x1f8
 beszel/internal/agent.(*Agent).gatherStats(_)
 	/app/internal/agent/agent.go:91 +0x1e5
 beszel/internal/agent.(*Agent).handleSession(0xc0000ddfd0?, {0x890f88, 0xc000214000})
 	/app/internal/agent/server.go:27 +0x32
 github.com/gliderlabs/ssh.(*session).handleRequests.func1()
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:261 +0x27
 created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 361
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:260 +0x4e7
 
 goroutine 1 [IO wait]:
 internal/poll.runtime_pollWait(0x7fd36d997cf8, 0x72)
 	/usr/local/go/src/runtime/netpoll.go:351 +0x85
 internal/poll.(*pollDesc).wait(0xc00012ae80?, 0x900000036?, 0x0)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
 internal/poll.(*pollDesc).waitRead(...)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Accept(0xc00012ae80)
 	/usr/local/go/src/internal/poll/fd_unix.go:620 +0x295
 net.(*netFD).accept(0xc00012ae80)
 	/usr/local/go/src/net/fd_unix.go:172 +0x29
 net.(*TCPListener).accept(0xc000102d00)
 	/usr/local/go/src/net/tcpsock_posix.go:159 +0x1e
 net.(*TCPListener).Accept(0xc000102d00)
 	/usr/local/go/src/net/tcpsock.go:372 +0x30
 github.com/gliderlabs/ssh.(*Server).Serve(0xc000120b40, {0x88d758, 0xc000102d00})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:250 +0x18c
 github.com/gliderlabs/ssh.(*Server).ListenAndServe(0xc000120b40)
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:351 +0x65
 github.com/gliderlabs/ssh.ListenAndServe({0xc0000123b8, 0x6}, 0x0, {0xc000093b60, 0x2, 0x13?})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/ssh.go:111 +0xb5
 beszel/internal/agent.(*Agent).startServer(0xc0001205a0, {0xc000018140, 0x50, 0x50}, {0xc0000123b8, 0x6})
 	/app/internal/agent/server.go:15 +0x1e5
 beszel/internal/agent.(*Agent).Run(0xc0001205a0, {0xc000018140, 0x50, 0x50}, {0xc0000123b8, 0x6})
 	/app/internal/agent/agent.go:80 +0x4c6
 main.main()
 	/app/cmd/agent/agent.go:40 +0x25c
 
 goroutine 318 [select]:
 net/http.(*persistConn).writeLoop(0xc00018a5a0)
 	/usr/local/go/src/net/http/transport.go:2519 +0xe7
 created by net/http.(*Transport).dialConn in goroutine 316
 	/usr/local/go/src/net/http/transport.go:1875 +0x15a5
 
 goroutine 386 [running]:
 	goroutine running on other thread; stack unavailable
 created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 385
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:260 +0x4e7
 
 goroutine 317 [select]:
 net/http.(*persistConn).readLoop(0xc00018a5a0)
 	/usr/local/go/src/net/http/transport.go:2325 +0xca5
 created by net/http.(*Transport).dialConn in goroutine 316
 	/usr/local/go/src/net/http/transport.go:1874 +0x154f
 
 goroutine 361 [chan receive]:
 github.com/gliderlabs/ssh.(*session).handleRequests(0xc000214000, 0xc000186230)
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:237 +0x50
 github.com/gliderlabs/ssh.DefaultSessionHandler(0xc000120b40, 0xc0000106a8, {0x88e1e0?, 0xc0001f2000?}, {0x890a88, 0xc00007b3b0})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:106 +0x13d
 created by github.com/gliderlabs/ssh.(*Server).HandleConn in goroutine 375
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:318 +0x4bb
 
 goroutine 376 [IO wait]:
 internal/poll.runtime_pollWait(0x7fd36d997e00, 0x72)
 	/usr/local/go/src/runtime/netpoll.go:351 +0x85
 internal/poll.(*pollDesc).wait(0xc0000c8280?, 0xc000155000?, 0x0)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
 internal/poll.(*pollDesc).waitRead(...)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc0000c8280, {0xc000155000, 0x1000, 0x1000})
 	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
 net.(*netFD).Read(0xc0000c8280, {0xc000155000?, 0x55d245?, 0xc0002fa010?})
 	/usr/local/go/src/net/fd_posix.go:55 +0x25
 net.(*conn).Read(0xc0002fa010, {0xc000155000?, 0xc0001de010?, 0x0?})
 	/usr/local/go/src/net/net.go:189 +0x45
 github.com/gliderlabs/ssh.(*serverConn).Read(0xc00019c100, {0xc000155000, 0x1000, 0x1000})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/conn.go:28 +0x4c
 bufio.(*Reader).Read(0xc000180240, {0xc00006a150, 0x4, 0xc0001de010?})
 	/usr/local/go/src/bufio/bufio.go:241 +0x197
 io.ReadAtLeast({0x88b120, 0xc000180240}, {0xc00006a150, 0x4, 0x4}, 0x4)
 	/usr/local/go/src/io/io.go:335 +0x90
 io.ReadFull(...)
 	/usr/local/go/src/io/io.go:354
 golang.org/x/crypto/ssh.(*gcmCipher).readCipherPacket(0xc00006a140, 0x764ae0?, {0x88b120, 0xc000180240})
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/cipher.go:373 +0x56
 golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc00018a240, 0x76d240?, 0x1)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/transport.go:147 +0x42
 golang.org/x/crypto/ssh.(*transport).readPacket(0xc00018a240)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/transport.go:130 +0x2b
 golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc00012e680, 0x0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:400 +0x37
 golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc00012e680)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:219 +0x39
 created by golang.org/x/crypto/ssh.newServerTransport in goroutine 375
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:164 +0x126
 
 goroutine 360 [chan receive]:
 github.com/gliderlabs/ssh.(*Server).handleRequests(0xc000120b40, {0x890a88, 0xc00007b3b0}, 0xc000186150)
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:323 +0x45
 created by github.com/gliderlabs/ssh.(*Server).HandleConn in goroutine 375
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:308 +0x2f6
 
 goroutine 374 [chan receive]:
 github.com/gliderlabs/ssh.(*Server).HandleConn(0xc000120b40, {0x88ff98, 0xc0002fa000})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:309 +0x37d
 created by github.com/gliderlabs/ssh.(*Server).Serve in goroutine 1
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:271 +0x1f8
 
 goroutine 349 [IO wait]:
 internal/poll.runtime_pollWait(0x7fd36d997bf0, 0x72)
 	/usr/local/go/src/runtime/netpoll.go:351 +0x85
 internal/poll.(*pollDesc).wait(0xc0000c8000?, 0xc0001b1000?, 0x0)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
 internal/poll.(*pollDesc).waitRead(...)
 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc0000c8000, {0xc0001b1000, 0x1000, 0x1000})
 	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
 net.(*netFD).Read(0xc0000c8000, {0xc0001b1000?, 0x55d245?, 0xc0002fa000?})
 	/usr/local/go/src/net/fd_posix.go:55 +0x25
 net.(*conn).Read(0xc0002fa000, {0xc0001b1000?, 0xc0000b6010?, 0x0?})
 	/usr/local/go/src/net/net.go:189 +0x45
 github.com/gliderlabs/ssh.(*serverConn).Read(0xc00019c000, {0xc0001b1000, 0x1000, 0x1000})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/conn.go:28 +0x4c
 bufio.(*Reader).Read(0xc000016240, {0xc00006a2e0, 0x4, 0xc0000b6010?})
 	/usr/local/go/src/bufio/bufio.go:241 +0x197
 io.ReadAtLeast({0x88b120, 0xc000016240}, {0xc00006a2e0, 0x4, 0x4}, 0x4)
 	/usr/local/go/src/io/io.go:335 +0x90
 io.ReadFull(...)
 	/usr/local/go/src/io/io.go:354
 golang.org/x/crypto/ssh.(*gcmCipher).readCipherPacket(0xc00006a2d0, 0x764ae0?, {0x88b120, 0xc000016240})
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/cipher.go:373 +0x56
 golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc0001206c0, 0x76d240?, 0x1)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/transport.go:147 +0x42
 golang.org/x/crypto/ssh.(*transport).readPacket(0xc0001206c0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/transport.go:130 +0x2b
 golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc0001e0000, 0x0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:400 +0x37
 golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc0001e0000)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:219 +0x39
 created by golang.org/x/crypto/ssh.newServerTransport in goroutine 374
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:164 +0x126
 
 goroutine 375 [chan receive]:
 github.com/gliderlabs/ssh.(*Server).HandleConn(0xc000120b40, {0x88ff98, 0xc0002fa010})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:309 +0x37d
 created by github.com/gliderlabs/ssh.(*Server).Serve in goroutine 1
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:271 +0x1f8
 
 goroutine 359 [chan receive]:
 golang.org/x/crypto/ssh.(*handshakeTransport).readPacket(0xc00012e680)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:209 +0x36
 golang.org/x/crypto/ssh.(*mux).onePacket(0xc0001861c0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:215 +0x2a
 golang.org/x/crypto/ssh.(*mux).loop(0xc0001861c0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:190 +0x25
 created by golang.org/x/crypto/ssh.newMux in goroutine 375
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:128 +0x16b
 
 goroutine 319 [chan receive]:
 golang.org/x/crypto/ssh.(*handshakeTransport).readPacket(0xc0001e0000)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:209 +0x36
 golang.org/x/crypto/ssh.(*mux).onePacket(0xc0001361c0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:215 +0x2a
 golang.org/x/crypto/ssh.(*mux).loop(0xc0001361c0)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:190 +0x25
 created by golang.org/x/crypto/ssh.newMux in goroutine 374
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/mux.go:128 +0x16b
 
 goroutine 320 [chan receive]:
 github.com/gliderlabs/ssh.(*Server).handleRequests(0xc000120b40, {0x890a88, 0xc00007a6f0}, 0xc000136150)
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:323 +0x45
 created by github.com/gliderlabs/ssh.(*Server).HandleConn in goroutine 374
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:308 +0x2f6
 
 goroutine 373 [select]:
 net/http.(*persistConn).writeLoop(0xc000120120)
 	/usr/local/go/src/net/http/transport.go:2519 +0xe7
 created by net/http.(*Transport).dialConn in goroutine 371
 	/usr/local/go/src/net/http/transport.go:1875 +0x15a5
 
 goroutine 372 [select]:
 net/http.(*persistConn).readLoop(0xc000120120)
 	/usr/local/go/src/net/http/transport.go:2325 +0xca5
 created by net/http.(*Transport).dialConn in goroutine 371
 	/usr/local/go/src/net/http/transport.go:1874 +0x154f
 
 goroutine 350 [select]:
 golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc0001e0000)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:293 +0x4fa
 created by golang.org/x/crypto/ssh.newServerTransport in goroutine 374
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:165 +0x165
 
 goroutine 385 [chan receive]:
 github.com/gliderlabs/ssh.(*session).handleRequests(0xc00007c000, 0xc000136230)
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:237 +0x50
 github.com/gliderlabs/ssh.DefaultSessionHandler(0xc000120b40, 0xc00019a138, {0x88e1e0?, 0xc0000c6000?}, {0x890a88, 0xc00007a6f0})
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:106 +0x13d
 created by github.com/gliderlabs/ssh.(*Server).HandleConn in goroutine 374
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/server.go:318 +0x4bb
 
 goroutine 377 [select]:
 golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc00012e680)
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:293 +0x4fa
 created by golang.org/x/crypto/ssh.newServerTransport in goroutine 375
 	/go/pkg/mod/golang.org/x/crypto@v0.28.0/ssh/handshake.go:165 +0x165
 
 goroutine 386 [running]:
 beszel/internal/agent.(*dockerManager).getDockerStats(0xc00006a6e0)
 	/app/internal/agent/docker.go:60 +0x1f8
 beszel/internal/agent.(*Agent).gatherStats(_)
 	/app/internal/agent/agent.go:91 +0x1e5
 beszel/internal/agent.(*Agent).handleSession(0xc0000dffd0?, {0x890f88, 0xc00007c000})
 	/app/internal/agent/server.go:27 +0x32
 github.com/gliderlabs/ssh.(*session).handleRequests.func1()
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:261 +0x27
 created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 385
 	/go/pkg/mod/github.com/gliderlabs/ssh@v0.3.7/session.go:260 +0x4e7`

Thought I would let you know :)

**Comment by henrygd** [comment]
Merging with #216
