### ISSUE TITLE
[FEATURE] Allow Alerts for "Bandwidth Average exceeds" higher than 99 MB/s

### ISSUE THREAD

**Issue by christianromeni** [henrygd/beszel#222]
As much as I like the sleek UI for selecting the % and °C for all other metrics, for Bandwidth it should be a input field instead of a slider.
I know, I can change the values manually in the settings... and it looks ok:

![image](https://github.com/user-attachments/assets/993989ca-a40a-4382-ab24-a03acab6a844)

but to have an input field to enter a number direct, could be a solution:

![image](https://github.com/user-attachments/assets/329ed615-cc12-4fca-9674-ff629f31dfdc)

**Comment by henrygd** [comment]
No problem, I can just increase the maximum value for this slider.

Probably makes sense to go to 125 MB/s (1 gigabit).

**Comment by dexedrine-01** [comment]
Hi!
1. It’s not very intuitive that 125 MB is roughly 1 Gbit. Why can’t we choose the measurement unit?
2. My server has a 20 Gbit/s port. How do I manually set the limit? I don’t need an alert at 1 Gbit/s.

**Comment by henrygd** [comment]
@dexedrine-01 See #468 

For now you should be able to manually change the number to whatever you want by creating the alert, then editing it through the alerts table in PocketBase.
