### ISSUE TITLE
Feature Request - Multiple Filesystems

### ISSUE THREAD

**Issue by JamsRepos** [henrygd/beszel#23]
If this already exists, please excuse me but it'd be grand if we could specify multiple filesystems to monitor within the variable as for Unraid users like myself, it would make it a lot easier to see each drive in the array's and pool's.

**Comment by peterbuga** [comment]
+1 on this too

**Comment by henrygd** [comment]
I'm soliciting opinions on this in #36, so please comment there if you have any thoughts.
