### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by alexzaitsev** [henrygd/beszel#231]
I want to compile the project by myself and run both hub&agent on my machine. 
I successfully finished [steps noted in the readme](https://github.com/henrygd/beszel/tree/main?tab=readme-ov-file#compiling) but after that, I was stuck trying to run `hub`:

```
% ./hub
Usage:
  beszel [command]

Available Commands:
  admin       Manages admin accounts
  migrate     Executes app DB migration scripts
  serve       Starts the web server (default to 127.0.0.1:8090 if no domain is specified)
  update      Update beszel to the latest version

Flags:
      --dev                    enable dev mode, aka. printing logs and sql statements to the console
      --dir string             the PocketBase data directory (default "beszel_data")
      --encryptionEnv string   the env variable whose value of 32 characters will be used
                               as encryption key for the app settings (default none)
  -h, --help                   help for beszel
  -v, --version                version for beszel

Use "beszel [command] --help" for more information about a command.
```
I cannot find `beszel` executable. 

Could you help me?

**Comment by henrygd** [comment]
`hub` is the right executable.

Use the `serve` subcommand to run the server:

```bash
./hub serve
```

Then when you run the agent, make sure you include your key:

```bash
KEY="..." ./agent
```

**Comment by alexzaitsev** [comment]
thanks @henrygd, it helped.
Where can I get the key? Seems this part is missed in the readme as well.

**Comment by alexzaitsev** [comment]
OK, seems I found it: `cat beszel_data/id_ed25519.pub`
`KEY="file content" ./agent`
Is this correct? 
```
p3ngu1n@p3ngu1n agent % KEY="key" ./agent
2024/10/28 15:57:51 INFO Detected root device name=disk3s1s1
2024/10/28 15:57:51 WARN Device not found in diskstats name=disk3s1s1
2024/10/28 15:57:51 INFO Using I/O fallback name=disk0
2024/10/28 15:57:51 INFO Detected network interface name=en0 sent=12277918669 recv=715606327833
2024/10/28 15:57:51 INFO Detected network interface name=awdl0 sent=792780 recv=44279418
2024/10/28 15:57:51 INFO Detected network interface name=en10 sent=16349783 recv=2540066
2024/10/28 15:57:51 INFO Starting SSH server address=:45876
```

**Comment by alexzaitsev** [comment]
I've added the system to admin dashboard based on the port produced by `./agent`:
<img width="1995" alt="Screenshot 2024-10-28 at 16 06 44" src="https://github.com/user-attachments/assets/bfafec9b-74bc-43b6-8bba-ec8744387a5d">

What are my next steps to explore the system? Should I be able to login as an agent? Or agent is something just to be monitored? Then why it has login/password. 

Thank you, just confused a little bit.

**Comment by henrygd** [comment]
When you start the server for the first time, make sure you go to the base url `/`, and not `/_/` (the PocketBase backend).

I recommend deleting your `beszel_data` directory and starting over.

You will see a screen like this to create your first user:

![login](https://github.com/user-attachments/assets/42b85342-4f9c-48a1-a5ff-cbf9a82cb507)

After that, it will put you in the Beszel dashboard, where you can click the "Add System" button to create your system and view your key.

**Comment by alexzaitsev** [comment]
Great, I ran it. 
I was confused because `./hub serve` provides PocketBase default URL to follow.
```
hub % ./hub serve
2024/10/28 22:24:44 Server started at http://127.0.0.1:8090
├─ REST API: http://127.0.0.1:8090/api/
└─ Admin UI: http://127.0.0.1:8090/_/
```

@henrygd do you think these things (1. running `./hub serve` when compiled; 2. using `http://127.0.0.1:8090` without `/_/`) worth mentioning in readme? I can add them if needed.

**Comment by henrygd** [comment]
We do mention in the [Installation > Binary](https://github.com/henrygd/beszel?tab=readme-ov-file#binary) section that you should run the serve command, but you're right that the compile section should be clearer and easier.

We're actually reworking the docs and transitioning to [standalone website](https://preview.beszel.dev/) instead of a big readme file. I'll improve the compilation instructions and maybe add a makefile.

The 'getting started' instructions will be much clearer and include screenshots. I'll make a note to mention that you should not go the the PocketBase UI on first run.

You're welcome to make a PR for readme improvements if you'd like, or contribute to the new docs site: https://github.com/henrygd/beszel-docs
