### ISSUE TITLE
[bug] newly added system can be stuck in endless loader

### ISSUE THREAD

**Issue by alexzaitsev** [henrygd/beszel#234]
I think this occurs only on the newly added system with insufficient recorded statistics. 

Steps:
1. go to Settings and set up bigger default time period. 
2. go to Main
3. go to the system
4. observe endless spinners

Video shows the steps + how changing time period fixes the loaders.

Video:
https://github.com/user-attachments/assets/2f3beb0c-e6f7-435b-8e6c-e5fcdcd2492f

@henrygd I can try to fix it if you're open for contributions. In this case I will appreciate any notes than can help me to do it.

**Comment by ArsFy** [comment]
#223
> Initial Chart Loading
> To me it seems logical to show a loading indicator if there are no records yet. They will populate eventually if you leave the page open for long enough.
> What would you suggest instead? Maybe a message that says no records have been populated yet?

My suggestion is add a loading text, but I haven't implemented this part yet. However, I should be submitting a pull request to fix this issue soon.

**Comment by ArsFy** [comment]
![image](https://github.com/user-attachments/assets/55e10f3a-5868-43b4-a255-e4d5727fbca6)

**Comment by alexzaitsev** [comment]
@ArsFy the design you're proposing is still confusing from my point of view. 

Loading spinner means **something is loading**. If we have a statement "No records have been populated" it means the **loading is done** so the loading spinner should be hidden.

The test itself can be better too, for example, "There are not enough records to display the chart". Anyway, having text is better than endless loading spinner.

**Comment by ArsFy** [comment]
@alexzaitsev You are right, but it does have some loading.

This is a difficult design cuz the data is actually real-time. If you open the window long enough, it will be successfully loaded into the data.

Maybe you have a better way to fix it? pls tell me, thank you.

**Comment by alexzaitsev** [comment]
agree with @henrygd, this is what I meant. Right now 2 conditions are mixed into a single one. they need to be separated

**Comment by ArsFy** [comment]
@alexzaitsev @henrygd I understand now, so I think I need to add a status to show whether the request was successful.

- Request successful but empty: display text
- Request pending: display only the loader

And, I think maybe changing it to `Waiting for enough records to display the chart` would be more appropriate?

**Comment by henrygd** [comment]
@ArsFy Exactly right.

I think that phrasing is good.

I can probably take care of this tomorrow if you don't want to deal with it.

**Comment by ArsFy** [comment]
@henrygd I finish the job (except for the Crowdin link), it is currently noon in SGT, but you can check my merge request tomorrow

**Comment by henrygd** [comment]
Thanks @ArsFy! I'll close the issue since it will be fixed in the next release.
