### ISSUE TITLE
Can the agent support more router architectures?

### ISSUE THREAD

**Issue by Viknopx** [henrygd/beszel#239]
Hello, could you compile an agent for the mipsle architecture? I want to use it on a router.

**Comment by henrygd** [comment]
I added a mipsle binary to the last release: https://github.com/henrygd/beszel/releases/tag/v0.6.2

It may not be added automatically for future releases, but you can build for mipsle easily on any computer that has Go:

```bash
# clone repository
git clone https://github.com/henrygd/beszel
# cd to project directory
cd beszel/beszel
# build agent
make build-agent OS=linux ARCH=mipsle
```

The agent binary will now be in the `./build` directory.
