### ISSUE TITLE
BUG: Incorrect disk usage for small partition

### ISSUE THREAD

**Issue by Wrykoulaka** [henrygd/beszel#261]
I have a small ram partition for logs (200 MB) which is shown wrongly:

![imagen](https://github.com/user-attachments/assets/72fff46b-b677-4f4a-8f09-5791ac6b0099)

![imagen](https://github.com/user-attachments/assets/e25abc5a-c536-42d4-94b9-891bfff5fd25)

![imagen](https://github.com/user-attachments/assets/2780a1cb-be2a-4127-b48b-ba1da2efd079)

The data seems to be OK in system_stats, so I assume is just a graphic bug?

![imagen](https://github.com/user-attachments/assets/84af0042-adb8-4475-be97-bbe59132a2e2)

**Comment by henrygd** [comment]
Thanks for pointing this out! It will be fixed in the next release.
