### ISSUE TITLE
Bandwidth tracking not being logged in Container

### ISSUE THREAD

**Issue by Resodx** [henrygd/beszel#27]
Perhaps a similar problem to the filesystem, where the network interface is not being identified by the container.

![image](https://github.com/user-attachments/assets/9eb4886f-0494-4b0c-a95d-db794619d5ac)

**Comment by henrygd** [comment]
Are you running the agent with docker? And if so, can you double check that you're using `network_mode: host`?

The docker container doesn't have access to your host interfaces if not in host network mode.

**Comment by Resodx** [comment]
> Are you running the agent with docker? And if so, can you double check that you're using `network_mode: host`?
> 
> The docker container doesn't have access to your host interfaces if not in host network mode.

Thanks for your reply. I'm really not using network-mode host.
For (cloudflared) reasons I use the hub in bridge mode on the same host as the agent, with the agent in network-mode host I couldn't connect on the hub using localhost, local ip, vlan...
I was only able to connect by passing the ip of the container with the agent in bridge as well.

**Comment by Resodx** [comment]
I don't know if it's possible to read the network interface like any other device, from `/sys/class/net/{network_interface}`

**Comment by henrygd** [comment]
I tried various other methods for getting access to network interface metrics, including mounting /proc and /sys inside the container without success. Also tried different base distros. Using the host network was the only thing that worked.

If someone knows of a different solution, I'm happy to try it out. But as of now I don't think it's possible to access host network interface stats without being in host network mode.

**Comment by henrygd** [comment]
This is a known and potentially unfixable limitation so I'm going to close the issue.
