### ISSUE TITLE
[QUSTION] No support for passive agent?

### ISSUE THREAD

**Issue by SKJoy** [henrygd/beszel#28]
Hi, this looks a really great great tool :)

Just wanted to ask, as I saw the Agent needs to be communicated by the Hub, so I believe LAN hosts are not supported with a Hub over Internet without a specific port forward from router?

Thank you again for such a wonderful tool. This one really excels UpTime Kuma in terms of multi user environment and Agent-Hub concept.

**Comment by henrygd** [comment]
Please see #16 

Maybe in the future.

If you have a public hub and private agents behind LAN, a possible solution for now is connecting via Wireguard or Cloudflare tunnel.
