### ISSUE TITLE
[Enhancement] Auto user creation for OIDC login and password login deactivation

### ISSUE THREAD

**Issue by maxbrueckl** [henrygd/beszel#303]
Right now, users need to be existing to be mapped and logged in via OIDC. It would be helpful to have the option for auto creation of said user on OIDC login request. To be more in line with a Single-sign-on philosophy.

This also opens up the possibility to disable password login for a group of users. This eliminates an attack vector and improves security.

**Comment by henrygd** [comment]
See #291 for instructions to allow auto user creation for OIDC. I will add an env var for this soonish.

Right now you can disable password login entirely but it cannot be customized to user groups. In the future we'll have MFA for password login as well.

I'll close the issue but let me know if you have questions or run into trouble with this.
