### ISSUE TITLE
Allow configuring listener addr on agent (reduce security exposure)

### ISSUE THREAD

**Issue by canidam** [henrygd/beszel#316]
The agent currently binds 0.0.0.0:$PORT

When running in 'onebox' mode, where hub and agent runs on the same machine, this expose an unnecessary port outside. This can be blocked by fw rules, but it would be good enhancement to allow configuring the addr using a parameter.

This allows onebox setup to listen only on localhost. (127.0.0.1:45876)

It's fairly minor change, I can open PR for that if accepted

**Comment by henrygd** [comment]
`PORT` accepts a port or an address:port, so you should be able to do `PORT=127.0.0.1:45876`. Let me know if that doesn't work for you.

I know it's a bit confusing. Maybe we should add a separate `ADDRESS` env var.

**Comment by canidam** [comment]
That would do, but I think it really better to change this to ADDRESS. Make much more sense
