### ISSUE TITLE
Docker Container Metrics

### ISSUE THREAD

**Issue by sthgi** [henrygd/beszel#32]
Wondering if Beszel could track Individual docker metrics the same way it does hosts.  So when we install the agent on a host with docker present it lists out all the docker containers and tracks them individually with cpu, memory and then we could alert on them.

Thanks,

**Comment by henrygd** [comment]
It tracks container CPU / memory and displays them in charts on the individual system pages. What would you like to see that's different from the current behavior?

Alerts for individual containers is a possibility in the future but probably not soon.

**Comment by sthgi** [comment]
Sorry I had just installed it so didn't realize the mouse over.  I guess if you ever do alerts maybe another breakout page with all the dockers listed with the resources next to it like in "All Systems".

Thanks again

**Comment by henrygd** [comment]
No worries. I'll close the issue since there's another issue on container alerts here: #40
