### ISSUE TITLE
Does it support Feishu Webhook

### ISSUE THREAD

**Issue by zz950115** [henrygd/beszel#328]

**Comment by henrygd** [comment]
Yes, you should be able to use a Feishu webhook using the [generic URL structure](https://containrrr.dev/shoutrrr/v0.8/services/generic/).

Looking at [Feishu documentation](https://www.feishu.cn/hc/en-US/articles/807992406756-use-the-webhook-trigger) you can set up the webhook to consume JSON.

Add `?template=json` to your URL and it will send a JSON post request with `title` and `message` keys:

```
generic://webhook.site/6dead0e1-372d-481e-be43-b43ce56b2aa9?template=json
```

```json
{
  "message": "CPU averaged 5.71% for the previous 2 minutes.\n\nhttp://localhost:8090/system/localhost",
  "title": "localhost CPU above threshold"
}
```

You can use [webhook.site](https://webhook.site/#!/) to test your notification.

**Comment by zz950115** [comment]
Thank you for completing the configuration
