### ISSUE TITLE
Request: New environment variable BASE_URL

### ISSUE THREAD

**Issue by ARC-XX** [henrygd/beszel#331]
For the sake of system integration or connection encryption, please add support for custom BASE_URL, so that we can customize the URL prefix.

Such as BASE_URL=/aaaa-bbbb-cccc-dddd, then tail https://hostname/aaaa-bbbb-cccc-dddd to show dashboard;

**Comment by henrygd** [comment]
Duplicate of #33 

I will try to add support for this in the next couple of releases
