### ISSUE TITLE
Homepage Dashboard integration broken after 0.9.0 update

### ISSUE THREAD

**Issue by yurividal** [henrygd/beszel#336]
Did the api endpoint change on the latest update?
[Homepage](gethomepage.dev) widget integration no longer works.

**Comment by henrygd** [comment]
Sorry, I just updated the release notes as I completely forgot to mention this.

The `/api/admins/*` endpoints were replaced with the `_superusers` auth collection in [PocketBase 0.23.0](https://github.com/pocketbase/pocketbase/releases/tag/v0.23.0).

Looks like shamoon already figured out the problem and has added compatibility for the new version: https://github.com/gethomepage/homepage/pull/4439 (thank you!)

My mistake, I should have thought ahead and given forewarning about that change.

**Comment by yurividal** [comment]
No need to apologize! Thank you for your work!

**Comment by aspecterman** [comment]
Apologies, but still not working for me. Deployed Hub via Docker - what do I need to do to get authentication working again please?

**Comment by awlobo** [comment]
> Apologies, but still not working for me. Deployed Hub via Docker - what do I need to do to get authentication working again please?

I guess Homepage should make a release with the new changes

**Comment by henrygd** [comment]
Yes, it will be fixed in the next release of Homepage.

To be clear, it's my fault, not Homepage / shamoon.

I don't anticipate further changes to the API, but if it happens I'll try to submit fixes or communicate with authors of integrations ahead of time.

**Comment by aspecterman** [comment]
> Yes, it will be fixed in the next release of Homepage.

Hi, just updated to the latest version of Homepage and the widgets are working beautifully - thank you very much for your hard work, so appreciated.

**Comment by rcbop** [comment]
Hey @yurividal can you change the strict equals `===` to a normal js equals `==`:
https://github.com/gethomepage/homepage/pull/4439/files#r1896937590

**Comment by rcbop** [comment]
Opened this to try to fix it https://github.com/gethomepage/homepage/pull/4488

**Comment by yusuf-madkour** [comment]
Integration is still not working for me on last versions of both Beszel and Homepage.

**Comment by henrygd** [comment]
@yusuf-madkour Make sure you use `version: 2` as shown below, and the user/pass should be for a superuser that can log in to PocketBase (`<your-url>/_/`).

https://gethomepage.dev/widgets/services/beszel/

Please [open a support discussion](https://github.com/henrygd/beszel/discussions/new?category=support) if this still doesn't work.

**Comment by yusuf-madkour** [comment]
Did both, opened a discussion over at homepage, did some troubleshooting too. Boils down to unexplained autheentication failure.
