### ISSUE TITLE
Suggestions for Data Collection

### ISSUE THREAD

**Issue by mylo114514** [henrygd/beszel#339]
Thank you very much for contributing such an excellent project.

I believe there is still room for improvement in the data collection aspect.

Some services cannot be directly exposed to the internet, and opening ports may pose security challenges. 
Changing to an agent that actively reports data to the hub might be more secure. 

Additionally, having the hub initiate connections proactively could lead to performance challenges for the host running the hub, especially when there are a large number of nodes.

BTW, I think you could open a donation channel to encourage better maintenance of the project. I would be more than happy to buy you a cup of coffee. :D

**Comment by henrygd** [comment]
Thanks, I'm glad you find it useful!

This is on my list to add. I'm going to close the issue because we have an existing discussion about it in #51.

I do have a [Buy Me a Coffee page](https://buymeacoffee.com/henrygd). Support is obviously appreciated but not expected or required!
