### ISSUE TITLE
Binary Hub systemd service example shows User=root

### ISSUE THREAD

**Issue by dabell-cc** [henrygd/beszel#354]
I think this is just a documentation gap, but why would the service need to run as root?

As seen in the manual steps for binary installation of the hub, the [example systemd service](https://beszel.dev/guide/hub-installation#create-a-service-optional) sets User=root. 
It seems like poor practice from a security perspective and even the [install.sh](https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-hub.sh) for the hub creates a 'beszel' user to set for the service unit configuration.

Is using root necessary in this context (binary hub manual install)?
If not, should the documentation instead suggest creating a system account user, or just highlight the security risk of allowing a service to run as root?

**Comment by henrygd** [comment]
Good point. I updated the docs to specify that a non-root user can be used if the user has write access to the working directory.
