### ISSUE TITLE
OpenID May need claim or Role? 

### ISSUE THREAD

**Issue by Node815** [henrygd/beszel#4]
I don't see it as one you listed for supported OIDC providers, but I am using Authentik.  I have it connected, and it calls Authentik as it should and returning from the authentication flow back to the app, it says there's a login failure.  

![image](https://github.com/user-attachments/assets/2e45809d-ac70-444a-ad4e-ab4a2ce2da79)

I also changed the report IP from the one you list to my FQDN so not sure why that isn't showing (I use Cloudflare Tunnels to point to it).  

Authentik shows these as the respective URL's (with redactions)

![image](https://github.com/user-attachments/assets/b2f1b88c-043c-4484-a2f3-80cce8209c1a)

How I have it set in the hub:
![image](https://github.com/user-attachments/assets/36f213ea-86be-4d2c-8eee-8ceb9df54731)

**Comment by henrygd** [comment]
I'll look into this but probably won't be able to get to it for at least a few days.

Just to confirm, does the user you're logging in as have a record in the PocketBase users table already with the same email and / or username?

**Comment by Node815** [comment]
Just my user which matches the same email address.

**Comment by MFYDev** [comment]
@henrygd @Node815 I can solve this issue. His user api url is wrong, it should be /userinfo/ but he is using the app url

**Comment by Node815** [comment]
@MFYDev Thanks!  Marking this as closed.  I was thrown with the 
![image](https://github.com/user-attachments/assets/1e478947-c731-41cb-ba3a-031c23404243)

This is now resolved!

**Comment by henrygd** [comment]
Perfect, thanks @MFYDev :+1:
