### ISSUE TITLE
[Enhancement] Binary one liner command install or bash script install

### ISSUE THREAD

**Issue by MFYDev** [henrygd/beszel#41]
Previously mentioned here https://github.com/henrygd/beszel/pull/14#issuecomment-2251234567

And here https://github.com/henrygd/beszel/discussions/38#discussioncomment-10163995

I have the one liner command working properly and tested on my server already, and the one liner needs to be a little bit more polished so that I can make sure it won't break any system related stuff.

Since I am a go-lang newbie, I can give it a shot to create the PR, also if you have time and want to do by yourself I can send you the one liner command.

I actually think making the one liner to be displayed above or below to the "Copy docker compose" will be the best, adding a down arrow there to let the use choose

![image](https://github.com/user-attachments/assets/7dbd4369-5716-447b-8594-03a5ad0cc981)

Make the issue here so that everybody can trace it and also please let me know if you have any better ideas

**Comment by henrygd** [comment]
Thank you for helping with this!

If you already have something mostly working in bash then there's no need to rewrite in go.

Another option for presentation is to have an additional field that says something like "Install method" with a select field to choose between Docker or Binary. We could save the user's preference this way too.

The button could change between "Copy docker compose" or "Copy install script" depending on the choice.

Other quick thoughts:

We should be able to grab their username from `$USER` or `whoami`.

It would be nice to have a prompt verifying that the current directory is where they want to save the agent binary, so they don't move it afterward. This could be skipped with a `--silent` flag to allow it to be automated.

We might want to specify in the button that this is for linux with something like "Copy Linux installer." 

I'm going to be off the computer for at least the next 15 hours but will be back at some point tomorrow.

**Comment by MFYDev** [comment]
> Another option for presentation is to have an additional field that says something like "Install method" with a select field to choose between Docker or Binary. We could save the user's preference this way too.

> The button could change between "Copy docker compose" or "Copy install script" depending on the choice.

Yeah exactly that is what my picture mean. This is the best solution I think

> We should be able to grab their username from $USER or whoami.

> It would be nice to have a prompt verifying that the current directory is where they want to save the agent binary, so they don't move it afterward. This could be skipped with a --silent flag to allow it to be automated.

Make sense. Because currently my one liner just simply run as root and save it to /user/local/bin/, but running as root will have the possibility for newbie user to break the system, I need to refactor the command.

> I'm going to be off the computer for at least the next 15 hours but will be back at some point tomorrow.

No rush at all, just enjoy a good Friday night and weekend!

**Comment by henrygd** [comment]
This has been kindly taken care of by @delta-whiplash in #77
