### ISSUE TITLE
PiKVM works with beszel-agent

### ISSUE THREAD

**Issue by sthgi** [henrygd/beszel#43]
Not an issue but PiKVM works with beszel-agent_linux_arm.tar.gz.

Thanks,

**Comment by henrygd** [comment]
Nice, good to hear!

**Comment by jacobslusser** [comment]
> Not an issue but PiKVM works with beszel-agent_linux_arm.tar.gz.
> 
> Thanks,

@sthgi can you please post or send instructions for installing on PiKVM?

**Comment by henrygd** [comment]
@jacobslusser Looks like sthgi is using the `beszel-agent_linux_arm` binary, which you can find on the [release page](https://github.com/henrygd/beszel/releases/latest).

I'd recommend selecting the "Binary" option when adding the PiKVM in the hub, then copying the command and running it in a terminal on your PiKVM.

If the install command doesn't work for some reason, let me know and I'll fix it to work with PiKVM.

Alternatively, you can manually download and run the binary file, or even compile it yourself. Check the docs here: https://beszel.dev/guide/agent-installation#binary

**Comment by sthgi** [comment]
I manually downloaded the binary like @henrygd said.  I place the binary in /usr/bin/ and create service here:
/etc/systemd/system/beszel-agent.service

Here is contents of service:

[Unit]
Description=Beszel Agent Service
After=network.target

[Service]
Environment="KEY=ssh-whatever yours is"
ExecStart=/usr/bin/beszel-agent
Restart=always

[Install]
WantedBy=multi-user.target

Then you can update with beszel-agent update

**Comment by jacobslusser** [comment]
Thank you both. The binary install script from the Beszel hub worked perfectly.
