### ISSUE TITLE
Monitor different network than docker's bridge

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#45]
Hello,

I'm running hub and agent on the same host with bridged networking in docker; only issue I have is that I cannot see stats for the "real" network host's interface.. Since docker containers are supposed to be isolated I guess there's no way to monitor e.g. eth0, right?

Thanks

**Comment by JamsRepos** [comment]
Why aren't you running the agent on the host?

**Comment by roughnecks** [comment]
> Why aren't you running the agent on the host?

What do you mean? I AM running the agent on the host, how could I not to? I'm NOT running the docker container on the host network though, but in a bridge, because I wouldn't like to expose it.

**Comment by JamsRepos** [comment]
Yeah, you’ve lost me. They’re both containers.  I have the network mode set to host for the agent container and my eth0 is logged perfectly fine. 

I don’t think you can access eth0 without putting it on the host rather than bridge. What do I know though.

**Comment by henrygd** [comment]
I tried various other methods for getting access to network interface metrics, including mounting /proc and /sys inside the container without success. Also tried different base distros. Using the host network was the only thing that worked.

So currently the options are:

1. Use host network and get access to metrics for host interfaces.
2. Don't use host network and don't get network metrics. Everything else should work the same.

If someone knows of a different solution, I'm happy to try it out. But as of now I don't think it's possible to access host network interface stats without being in host network mode.
