### ISSUE TITLE
Send alarm via Telegram Bot

### ISSUE THREAD

**Issue by cichy1173** [henrygd/beszel#47]
Hello. Beszel looks amazing, especially as that lightweight service. I see that the Beszel supports simple alarms, which I quite care about. Unfortunately, I don't see an option to send the information somewhere further. 
Personally, I care about sending information about the problem via a bot on Telegram. Telegram bots can be handled using curl as below.

```bash
curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_API/sendMessage" -d chat_id="$TELEGRAM_BOT_CHAT_ID" -d text="$message" -d parse_mode="MarkdownV2"
```

Such a command contains the bot's API key, chat ID and payload with the message. Is it possible to handle alerts like this with Beszel?

**Comment by henrygd** [comment]
It should be in the future.

I just made a discussion to get opinions on the implementation, so let's move the conversation there: #49
