### ISSUE TITLE
[BUG] When restarting a container with Portainer it vanishes from Beszel's metrics

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#48]
Hi,

If I restart any of my other docker containers with Portainer, Beszel fails to detect it afterwards; it doesn't show up anymore in the popup for docker's cpu/memory stats.
If I do a `docker compose down` followed by `docker compose up -d` there's no issue for Beszel detecting it.

**Comment by henrygd** [comment]
Thanks, looking into it.

**Comment by henrygd** [comment]
Should be fixed now in 0.1.1.

Let me know if you see it happen again.

**Comment by roughnecks** [comment]
Looks like it's fixed now. Thanks :)
