### ISSUE TITLE
[ documentation ] Add instructions for compiling to the README

### ISSUE THREAD

**Issue by yonas** [henrygd/beszel#53]
From https://github.com/henrygd/beszel/issues/35#issuecomment-2254257367

> I need to add instructions for compiling to the readme.
> 
> The agent is straightforward, but the hub embeds the website files in the binary, so you have to install the site dependencies and build the site before it's possible to compile.

**Comment by henrygd** [comment]
Thanks, I actually did add it not too long after I mentioned it :smile: 

Forgot to edit my comment to say that it was done.

https://github.com/henrygd/beszel/blob/main/readme.md#compiling
