### ISSUE TITLE
[Question] Application URL

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#54]
Hello,
the Application URL was automatically set to:

![image](https://github.com/user-attachments/assets/773c0d1f-427c-4a3d-a0a1-5eba50e0013a)

and email alerts and notifications are using that.. can I safely change it to the public https URL on which I'm serving Beszel by nginx?

Thanks

**Comment by henrygd** [comment]
Yes, please update it. After doing so you should see the correct URL in emails.

**Comment by roughnecks** [comment]
Thanks, will do.
