### ISSUE TITLE
Failed to get server stats: unexpected end of JSON input

### ISSUE THREAD

**Issue by mrnico76** [henrygd/beszel#57]
Hello, 

I've a problem with beszel agent. I use it in a docker and I can't add the agent client to the dashboard, because of this error: Failed to get server stats: unexpected end of JSON input

I've also checked the agent's logs, and i've only noticed this error: Error getting container stats: mailcowdockerized-netfilter-mailcow-1 cpu pct greater than 100: 3.308239611496335e+10

**Comment by henrygd** [comment]
What version of Docker on the agent system (`docker -v`)?

Try restarting Docker. `sudo systemctl restart docker` if on linux.

Is that error only with the one container? Approximately how many other containers are you running on the system?

**Comment by mrnico76** [comment]
Docker version 27.1.1, build 6312585

I've restarted Docker and It worked until this container started "mailcowdockerized-netfilter-mailcow-1".

I think the error is only with this container and I've 55 containers running

**Comment by henrygd** [comment]
Try 0.1.1 whenever you have a chance to upgrade and see if that fixes the problem. No rush.

**Comment by mrnico76** [comment]
I've upgraded to 0.1.1, but It didn't fixed my problem. Now I have no error in the agent's docker logs, but I still have this error: Failed to get server stats: unexpected end of JSON input

**Comment by henrygd** [comment]
Can you check that the API is returning valid JSON for that container?

Use `docker ps` to list containers, then copy the container's ID.

Then use curl to make a request to the API (replace `d07d19594b6e` with your container ID):
```
curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" "http://localhost/containers/d07d19594b6e/stats?stream=0&one-shot=1"
```

Post the response here please, or just compare with the response for another container ID to make sure everything is present.

**Comment by theRealBassist** [comment]
Just want to pop in to say that I have the exact same issue. 

When I make an API request on the agent system in the manner you mentioned I get the following:

```
{"read":"2024-08-07T01:49:25.145515375Z","preread":"0001-01-01T00:00:00Z","pids_stats":{"current":12,"limit":38321},"blkio_stats":{"io_service_bytes_recursive":null,"io_serviced_recursive":null,"io_queue_recursive":null,"io_service_time_recursive":null,"io_wait_time_recursive":null,"io_merged_recursive":null,"io_time_recursive":null,"sectors_recursive":null},"num_procs":0,"storage_stats":{},"cpu_stats":{"cpu_usage":{"total_usage":407628000,"usage_in_kernelmode":108573000,"usage_in_usermode":299054000},"system_cpu_usage":2452834380000000,"online_cpus":10,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"precpu_stats":{"cpu_usage":{"total_usage":0,"usage_in_kernelmode":0,"usage_in_usermode":0},"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":8105984,"stats":{"active_anon":7434240,"active_file":0,"anon":7434240,"anon_thp":0,"file":0,"file_dirty":0,"file_mapped":0,"file_writeback":0,"inactive_anon":0,"inactive_file":0,"kernel_stack":196608,"pgactivate":0,"pgdeactivate":0,"pgfault":4012,"pglazyfree":0,"pglazyfreed":0,"pgmajfault":0,"pgrefill":0,"pgscan":0,"pgsteal":0,"shmem":0,"slab":327024,"slab_reclaimable":100488,"slab_unreclaimable":226536,"sock":0,"thp_collapse_alloc":0,"thp_fault_alloc":0,"unevictable":0,"workingset_activate":0,"workingset_nodereclaim":0,"workingset_refault":0},"limit":10737418240}}
```

this is running version 0.1.1 and I have verified that the host can see the agent by running telnet to the specified host and port.

**Comment by henrygd** [comment]
@mrnico76 Good to hear, though it does seem strange that that would fix it. Let me know if it happens again.

@theRealBassist Thanks for the info! That looks like a stopped container though, as it doesn't have network or blkio_stats. Can you try with a running container?

I apologize as I was going to add more logs to the release today to try to debug this but ended up forgetting about it.

If you'd like I can upload a docker image or binary here that includes the extra logs.

**Comment by theRealBassist** [comment]
> @mrnico76 Good to hear, though it does seem strange that that would fix it. Let me know if it happens again.
> 
> @theRealBassist Thanks for the info! That looks like a stopped container though, as it doesn't have network or blkio_stats. Can you try with a running container?
> 
> I apologize as I was going to add more logs to the release today to try to debug this but ended up forgetting about it.
> 
> If you'd like I can upload a docker image or binary here that includes the extra logs.


Hey, sorry for taking some time. 

The container was definitely running at the time. Before you worry about the extra logging let me try rebooting the whole server when I get home from work tonight. I'm starting to see some issues with a few other containers which could definitely just be an issue with me not keeping up with updates, or it could be some weird virtualization crap. I'll get back to you in about 5 hours!

**Comment by theRealBassist** [comment]
@henrygd My greatest apologies for taking an extra day.

I restarted my vm and recreated the agent stack, and now it works fine.

My best guess, from past experience, is that it's probably some interaction between the hypervisor, the vm, and the docker daemon. That said, it could also be some error in the startup process of the agent/host for beszel, but I would hesitate to assume it's an issue on your end.

Hopefully if anyone else runs up with this issue you can just advise them to restart their server?

**Comment by henrygd** [comment]
I'll close this issue since it's working for you now.

For anyone here in the future, please see #103 which appears to be related.
