### ISSUE TITLE
Unable to login via OIDC on iOS / iPadOS

### ISSUE THREAD

**Issue by BrentOates** [henrygd/beszel#6]
This has definitely been a bit of a game changer in terms of a quick setup monitoring suite! I never had the time to setup a full stack so this has been an amazing development - thank you!
Equally the simplicity of the statistics page is extremely easy to parse at a glance too without having to configure monitoring graphs - another big thanks!

When logging in to Beszel on a desktop OS, I can click to login with a configured OIDC provider, which correctly opens a new window to complete the auth flow.

However, if I repeat that on a mobile device, when I click to login via OIDC, the wheel starts spinning but does not redirect to another page or open a new tab. I'm assuming this is a limitation of Safari on iOS expecting the tab to be rerouted rather than a new window to be opened? 

Let me know if there's any helpful information I can share, a bit limited as without a Mac I can't pull any logs from Safari on iOS!

**Comment by MFYDev** [comment]
You actually can pull logs from the ios Safari when you use wire to connect the iPhone to the Macbook. 

https://www.browserstack.com/guide/how-to-debug-on-iphone

here is the link if it can help

**Comment by henrygd** [comment]
Thanks!

I don't have an iOS device but was able to replicate this using Safari on Browserstack.

For some reason Chrome works properly. It shows a message that the popup is blocked, but you can click the message to show the popup. Not sure why that's the case as my understanding was that all browsers on iOS are Safari wrappers.

I'll look further into it when I have time but there are a couple other things ahead of this in the queue.

**Comment by henrygd** [comment]
Follow up question: If you don't mind, I'm curious to know what OIDC software you're using.

There's an open issue currently where someone is having a problem with Authentik. I tested a while back with Zitadel and it was working properly, so I'm just trying to get an idea of what's working and what's not.

**Comment by MFYDev** [comment]
I am using Authentik OIDC with Beszel without any issues now. Authentik for me is all fine

**Comment by BrentOates** [comment]
Unfortunately I don't have a Mac to pull logs! 
I'm using Authelia currently, but I'll wire up a few other providers and see what impact that has. Hopefully I can get a dev environment running to try debug further. 

I recall I've only run into this with other sites where their OIDC flow goes via another window rather than redirecting from the current page.

**Comment by henrygd** [comment]
Found this related issue on Pocketbase: https://github.com/pocketbase/pocketbase/discussions/3563

It may be due to calling the auth method inside an async click handler. I'll try refactoring that to see if it fixes the issue.

**Comment by MFYDev** [comment]
https://github.com/henrygd/beszel/issues/15

Just found this issue is solved. Please refer to it to check if there are any similar settings

**Comment by BrentOates** [comment]
> #15
> 
> Just found this issue is solved. Please refer to it to check if there are any similar settings

I've tried it with GitHub Auth as well, just spins the same without redirecting so not Authelia specific I'm afraid!

**Comment by henrygd** [comment]
I think I figured this out. It's an iOS / Safari specific thing where I needed to manually open the popup and set the URL. Otherwise Safari silently blocks it.

I didn't finish the auth process on browserstack, but I can at least get to my login now.

I'll have it out tomorrow in the next release.

**Comment by henrygd** [comment]
Possible fix out now in [0.1.1](https://github.com/henrygd/beszel/releases/tag/v0.1.1)

**Comment by BrentOates** [comment]
I can confirm using 0.1.1 has resolved this!
Thank you for digging into it 😃

**Comment by henrygd** [comment]
Awesome, that was quick!

I'll go ahead and close the issue now, but will reopen if it's not fixed for anyone else.
