### ISSUE TITLE
[Feature Request] - Docker socket proxy config

### ISSUE THREAD

**Issue by arcoast** [henrygd/beszel#60]
Although the beszel-agent container mounts `docker.sock` as `ro` as far as I'm aware that actually doesn't have much advantage as it still allows the potential for privilege escalation.

I'd love the ability to configure the beszel agent to use a docker socket proxy such as [linuxserver/docker-socket-proxy](https://github.com/linuxserver/docker-socket-proxy) rather than mount the docker.sock directly.

**Comment by henrygd** [comment]
Good idea, I'll look into it for the next release.

**Comment by InnocentRain** [comment]
This is a great idea, i'm just in the process of setting up my system and not being able to use a socket proxy is a bit off-putting.

**Comment by henrygd** [comment]
I added this a couple days ago. It will be in the next release.

**Comment by henrygd** [comment]
This is out now in 0.1.2.

Use the `DOCKER_HOST` environment variable instead of mounting the socket.

Let me know if you have any trouble with it!
