### ISSUE TITLE
[Question] Is the data retention configurable ? 

### ISSUE THREAD

**Issue by mikekuzak** [henrygd/beszel#61]
Hi,

Is there a way to set the retention time period for the data ? Like max 7days?

Thanks

**Comment by henrygd** [comment]
Not as of now.

However, it doesn't keep every one hour record for 30 days.

There's a cleanup operation once an hour that deletes 1 hour records older than 1 hour, 12 hour records older than 12 hours, etc.

I tried to be pretty careful about how much data needs to be stored.

**Comment by henrygd** [comment]
Closing this issue to consolidate data retention discussion to #114
