### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by NightHawkATL** [henrygd/beszel#63]
Just found this and installed the "server" on one of my docker hosts. I then added the agents to my 3 other docker hosts. Those are able to be updated with the docker pull. I am unable to get "beszel-agent update" to work on all of the hosts and VMs that I installed the agent on as a system service using the curl command to install and configure. Should I just re-run the curl command and restart the service? Planning to make an ansible playbook for this so I just need to know the correct approach.

**Comment by henrygd** [comment]
That approach works, but I'd also like to fix the update command if it's broken.

Just to be clear, you're running the agents as binaries, right? And running `./beszel-agent update`?

If running the hub as a binary, the command would be `./beszel update`

Just tested linux amd64 and it seems to work. What version are you using?

**Comment by NightHawkATL** [comment]
> Just to be clear, you're running the agents as binaries, right? And running `./beszel-agent update`?

This works for me as well. The instructions don't mention the "./" so I didn't use it. Not used to doing updates like that as most are apt-based. I will start working on my playbook to get the rest updated.

Thanks!

**Comment by henrygd** [comment]
Yeah no worries, it's just a subcommand built into the binary so you have to run it on the file.

If you want the command to be available globally, you can put the file in `/usr/local/bin`, then you should be able to run it without the `./`
