### ISSUE TITLE
After upgrading to 0.1.1 I have no login screen anymore

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#64]
Hi,
all I see now is this: 

![image](https://github.com/user-attachments/assets/eae95306-b520-4bae-9389-4b82e9dfe6b7)

**Comment by henrygd** [comment]
Yikes, must be my mistake there.

Are you using `DISABLE_PASSWORD_AUTH` with OAuth / OICD?

**Comment by henrygd** [comment]
I can't seem to find a configuration that does this.

Can you double check that your auth provider is still enabled in `<your-url>/_/#/settings/auth-providers`?

Maybe it got disabled somehow.

**Comment by roughnecks** [comment]
> Yikes, must be my mistake there.
> 
> Are you using `DISABLE_PASSWORD_AUTH` with OAuth / OICD?

my bad, yes, I had `DISABLE_PASSWORD_AUTH` set to true.
