### ISSUE TITLE
Agent loses connetion

### ISSUE THREAD

**Issue by utlilb** [henrygd/beszel#66]
I have 10 agents all working great and 1 agent that is being a pain. Keeps flapping between online and offline. Logs show this:

{
  "id": "hifhpalx9op3xz6",
  "created": "2024-07-29 02:01:32.018Z",
  "updated": "2024-07-29 02:01:32.018Z",
  "data": {
    "err": "wait: remote command exited without exit status or exit signal"
  },
  "message": "Failed to get server stats: ",
  "level": 8
}

**Comment by henrygd** [comment]
What os / arch are you running the problem agent on? Is it the same as the others? Is it in a virtual machine or on a cloud provider?

Anything being logged on the agent side?

I can make a binary later today or tomorrow with more logs to try to debug this and some other issues.

**Comment by utlilb** [comment]
It's the same setup as 5 other systems that are working. Docker agent running on Ubuntu 24.04 vm. I didn't see anything in the agent logs but I can dig deeper. Those would just be the docker logs for the agent container right?

The only thing different is this vm has the hub and agent. could that be an issue? maybe i should try the binary agent instead of docker?

**Comment by henrygd** [comment]
> The only thing different is this vm has the hub and agent

If this is the only difference then it's most likely related.

How are you setting it up? Are you using host network for both? Or just using the system's public IP? Or doing something like the example I put in #73?

Whichever way you're doing I'd recommend trying a different one.

**Comment by utlilb** [comment]
I had it set up to use the IP of the system. Then I tried like you did in https://github.com/henrygd/beszel/issues/73. Still the same problem.

Running the binary agent now and it seems to have fixed the issue. Possibly a conflict or communication issue with docker agent and hub on the same machine.
