### ISSUE TITLE
[Feature Request] Provision System up front

### ISSUE THREAD

**Issue by svenvg93** [henrygd/beszel#70]
After installing the agent on multiple systems, and adding them to the hub everything is working like a charm. Thanks for this amazing tool! 

As a addition it would be nice to be able to add systems via a provisioning file. For example with a yaml file with the ip address/hostnames. This way it can be added to system enrollments like ansible etc. 

for example 
```
host:
 - 192.168.1.2,host1
 - 192.168.1.3,host2
```

**Comment by henrygd** [comment]
As of 0.6.2, systems can be managed in a `config.yml` file inside your data directory.

You can export your current systems by going to `/settings/config`.

Let me know if you run into any issues with this.
