### ISSUE TITLE
[Security] Backups are not encrypted and contain SSH private key

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#72]
Hi,

I believe this is an issue, especially when using S3 to upload backups.

**Comment by henrygd** [comment]
Good point, however all the major S3 providers encrypt data by default before saving to disk, right? Including MinIO if you self host.

Could be wrong about that. I'll look further into it regardless.

**Comment by roughnecks** [comment]
I had it set up a few hours ago - it was not encrypted.
Meanwhile, I'll tell the person who is sharing their S3 hosting with me to ask the provider.

**Comment by henrygd** [comment]
FWIW if you see the file in the storage provider's UI, that doesn't necessarily mean it's unencrypted on disk.

The provider may be assuming -- I think fairly -- that the account holder should have access to the file, and decrypting it on the fly so you can view it.

If you're sharing a storage account with someone else and don't want them to be able to view it, I don't know if that's an issue in the scope of this library.

In that case an easy alternative would be using [Kopia](https://github.com/kopia/kopia) or [Borg](https://github.com/borgbackup/borg), which encrypts the data folder prior to backing up to S3.

**Comment by roughnecks** [comment]
yeah, sure, it could be decrypted on the fly, but I also followed S3 Browser documentation, here: https://s3browser.com/amazon-s3-server-side-encryption.aspx
And looking at the properties of a file on our S3 it says "server-side-encrypted" => no

I will close this issue now anyway, until I have more info and maybe reopen it later on. Also thanks for the tips.

**Comment by henrygd** [comment]
No worries. According to Amazon, they do encrypt all objects and have since Jan 2023:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-encryption-faq.html


https://aws.amazon.com/blogs/aws/amazon-s3-encrypts-new-objects-by-default/

**Comment by roughnecks** [comment]
> No worries. According to Amazon, they do encrypt all objects and have since Jan 2023:

ahah, yeah, I also read about that, but our is a compatible S3 from an Italian provider :)
