### ISSUE TITLE
automated installation script

### ISSUE THREAD

**Issue by delta-whiplash** [henrygd/beszel#77]
Hello I writed this bash script to deploy the agent on some of my kubernetes machines running ubuntu it could be nice to add it to the repo to help people curl to install the agent on there machine 

you can use it like this : 
`./install.sh -k "your_ssh_key" -p 45876`

If no parameter is given, the script will enter interactive mode to obtain the ssh key from the user.
The port if not changed in the command paramaters will be 45876

A great add to the webui will be to give a command with a port choosed in the webui + the hub ssh key for one line deployment with curl to bash for named deployment (like I can do it in wazuh for exemple) or mass deployment

EDIT : I did a version an uninstaller and some documentation of the script throught the `-h` options : 

```
 ./install.sh -h
Beszel Agent installation script

Usage: ./install.sh [options]

Options: 
  -k  : SSH key (required, or interactive if not provided)
  -p  : Port (default: 45876)
  -u  : Uninstall the Beszel Agent
  -h  : Display this help message
```
```
#!/bin/bash

# Define default values
PORT=45876

# Read command line options
while getopts ":k:p:uh" opt; do
  case $opt in
    k) KEY="$OPTARG";;
    p) PORT="$OPTARG";;
    u) UNINSTALL="true";;
    h) echo "Beszel Agent installation script"; echo ""
       echo "Usage: ./install.sh [options]"; echo ""
       echo "Options: "
       echo "  -k  : SSH key (required, or interactive if not provided)"; echo ""
       echo "  -p  : Port (default: $PORT)"; echo ""
       echo "  -u  : Uninstall the Beszel Agent"; echo ""
       echo "  -h  : Display this help message"; echo ""
       exit 0;;
    \?) echo "Invalid option: -$OPTARG"; exit 1;;
  esac
done

if [ "$UNINSTALL" = "true" ]; then
  # Stop and disable the Beszel Agent service
  echo "Stopping and disabling the Beszel Agent service..."
  sudo systemctl stop beszel-agent.service
  sudo systemctl disable beszel-agent.service

  # Remove the systemd service file
  echo "Removing the systemd service file..."
  sudo rm /etc/systemd/system/beszel-agent.service

  # Reload the systemd daemon
  echo "Reloading the systemd daemon..."
  sudo systemctl daemon-reload

  # Remove the Beszel Agent directory
  echo "Removing the Beszel Agent directory..."
  sudo rm -rf /opt/beszel-agent

  # Remove the dedicated user for the Beszel Agent service
  echo "Removing the dedicated user for the Beszel Agent service..."
  sudo userdel beszel-agent

  echo "The Beszel Agent has been uninstalled successfully!"
else
  # Check if the distribution is supported
  if [ "$(cat /etc/os-release | grep '^ID=')" != "ID=debian" ] && [ "$(cat /etc/os-release | grep '^ID=')" != "ID=ubuntu" ] && [ "$(cat /etc/os-release | grep '^ID_LIKE=')" != "ID_LIKE=debian" ]; then
    echo "Error: This script only supports Debian and Ubuntu distributions."
    exit 1
  fi

  # If no SSH key is provided, ask for the SSH key interactively
  if [ -z "$KEY" ]; then
    read -p "Enter your SSH key: " KEY
  fi

  # Check if necessary packages are installed
  sudo apt update
  sudo apt install -y tar curl

  # Create a dedicated user for the service if it doesn't exist
  if ! id -u beszel-agent > /dev/null 2>&1; then
    echo "Creating a dedicated user for the Beszel Agent service..."
    sudo useradd -m -s /bin/false beszel-agent
  fi

  # Create the directory for the Beszel Agent
  if [ ! -d "/opt/beszel-agent" ]; then
    echo "Creating the directory for the Beszel Agent..."
    sudo mkdir -p /opt/beszel-agent
    sudo chown beszel-agent:beszel-agent /opt/beszel-agent
    sudo chmod 755 /opt/beszel-agent
  fi

  # Download and install the Beszel Agent
  echo "Downloading and installing the Beszel Agent..."
  curl -sL "https://github.com/henrygd/beszel/releases/latest/download/beszel-agent_$(uname -s)_$(uname -m | sed 's/x86_64/amd64/' | sed 's/armv7l/arm/' | sed 's/aarch64/arm64/').tar.gz" | tar -xz -C /opt/beszel-agent -f - beszel-agent
  sudo chown beszel-agent:beszel-agent /opt/beszel-agent/beszel-agent
  sudo chmod 755 /opt/beszel-agent/beszel-agent

  # Create the systemd service
  echo "Creating the systemd service for the Beszel Agent..."
  sudo tee /etc/systemd/system/beszel-agent.service <<EOF
[Unit]
Description=Beszel Agent Service
After=network.target

[Service]
Environment="PORT=$PORT"
Environment="KEY=$KEY"
ExecStart=/opt/beszel-agent/beszel-agent
User=beszel-agent
Restart=always

[Install]
WantedBy=multi-user.target
EOF

  # Load and start the service
  echo "Loading and starting the Beszel Agent service..."
  sudo systemctl daemon-reload
  sudo systemctl enable beszel-agent.service
  sudo systemctl start beszel-agent.service

  # Check if the service is running
  if [ "$(systemctl is-active beszel-agent.service)" != "active" ]; then
    echo "Error: The Beszel Agent service is not running."
    exit 1
  fi

  echo "The Beszel Agent has been installed and configured successfully! It is now running on port $PORT."
fi
```

**Comment by delta-whiplash** [comment]
An uninstall script aswell : 
```
#!/bin/bash

# Stop and disable the Beszel Agent service
echo "Stopping and disabling the Beszel Agent service..."
sudo systemctl stop beszel-agent.service
sudo systemctl disable beszel-agent.service

# Remove the systemd service file
echo "Removing the systemd service file..."
sudo rm /etc/systemd/system/beszel-agent.service

# Reload the systemd daemon
echo "Reloading the systemd daemon..."
sudo systemctl daemon-reload

# Remove the Beszel Agent directory
echo "Removing the Beszel Agent directory..."
sudo rm -rf /opt/beszel-agent

# Remove the dedicated user for the Beszel Agent service
echo "Removing the dedicated user for the Beszel Agent service..."
sudo userdel beszel-agent

echo "The Beszel Agent has been uninstalled successfully!"
```

**Comment by henrygd** [comment]
This looks awesome, thank you! It's better than what I would've done.

You can make a pull request if you want a contribution. I think it would be good to put it in `/supplemental/scripts/install-agent.sh`

I'll test it out and merge later today, then add to the readme and eventually integrate with the web interface.

One comment - if we eventually expand this script to include an option for installing the hub, or make a dedicated script for that, it might be nice to have both the hub and agent under the same user. In which case `beszel` would work better than `beszel-agent`. What are your thoughts on that? I suppose there's a slightly higher chance that an existing user would be named beszel.

**Comment by delta-whiplash** [comment]
> This looks awesome, thank you! It's better than what I would've done.
> 
> You can make a pull request if you want a contribution. I think it would be good to put it in `/supplemental/scripts/install-agent.sh`
> 
> I'll test it out and merge later today, then add to the readme and eventually integrate with the web interface.
> 
> One comment - if we eventually expand this script to include an option for installing the hub, or make a dedicated script for that, it might be nice to have both the hub and agent under the same user. In which case `beszel` would work better than `beszel-agent`. What are your thoughts on that? I suppose there's a slightly higher chance that an existing user would be named beszel.

am gonna take a look at this when I will be home :)

**Comment by delta-whiplash** [comment]
@MFYDev I've created a pull request (#82) that implements the semi-automatic installation process for now.

Next, I'll look into implementing the one-click installation feature from the Hub with some curl to bash with the ssh-key included. 😊

**Comment by MFYDev** [comment]
Nice looks great. I am pretty busy on my work this week and I will take a deeper look later! Thanks!

**Comment by henrygd** [comment]
This has been merged. Thanks again for making the scripts!

I tweaked them a bit to work with other distros (tested Arch, CentOS, and Ubuntu) and also made it so it only installs tar / curl if they're not already installed. Seems to work great but please let me know if you see any issues with my changes!

I made a guide for installing [here](https://github.com/henrygd/beszel/blob/main/supplemental/guides/systemd.md) and just linked it from the readme.

I'll integrate it with the web UI at some point so there's no need to work on that end of things unless you really want to give it a try. Please be aware that this is the first time I've used React in about five years after moving to Svelte, so it may not follow the absolute best practices.
