### ISSUE TITLE
[Feature Request] Show disk size in the disk information

### ISSUE THREAD

**Issue by svenvg93** [henrygd/beszel#79]
It will be usefull to also see how much size is there in total. Currently in the disk usage graph it only shows how much disk size is used, but it does not tell much as you don't know who big the disk is.
So it shows three lines for; 
- Disk size 
- Used space 
- Free space (Optional)

**Comment by henrygd** [comment]
The y-axis is based on the disk size, so the largest value should be the total size of the disk. Let me know if that's not accurate on your system.

I can also put used percent in the tooltip if that would be helpful.

**Comment by svenvg93** [comment]
I just noticed that 😅 , that will do . Thanks for this awesome tool!

**Comment by henrygd** [comment]
No worries!
