### ISSUE TITLE
Docker Memory Usage Empty

### ISSUE THREAD

**Issue by ameer1234567890** [henrygd/beszel#81]
I have setup beszel on 4 different home lab hardware and everything is working perfectly, except for docker memory usage being empty (shows 0 MiB for all docker containers), on one of the servers. Notably, docker memory usage works fine on all the other 3 servers. I checked agent logs and there are no error messages.

Agent logs:
```
2024/07/31 19:06:45 Found network interface: eth0 (24707452515 recv, 10845671307 sent)
2024/07/31 19:06:45 Found network interface: tailscale0 (234298990 recv, 422972178 sent)
2024/07/31 19:06:45 Starting SSH server on :45876
```

Screenshot:
![Screenshot 2024-08-01 003549](https://github.com/user-attachments/assets/5995b94c-c959-4613-b4b0-166d24013cfa)

**Comment by henrygd** [comment]
Try running `docker stats --no-stream` to see if that also shows 0.

Likely related to #10 and you need to enable cgroup memory accounting.
