### ISSUE TITLE
[Feature Request] running kernel version

### ISSUE THREAD

**Issue by 0x5f3** [henrygd/beszel#83]
Along with status, IP, uptime, and CPU stats, add the running kernel version.

**Comment by steveiliop56** [comment]
@henrygd can I try to implement this?

**Comment by henrygd** [comment]
@steveiliop56 Sure, you can try if you'd like.

You can reference this commit where I pulled in the system's hostname: 3e95269a7c7aa48600e83818ca576b40890d8c17

There's a property `KernelVersion` in that struct: https://pkg.go.dev/github.com/shirou/gopsutil/v4/host#InfoStat

**Comment by steveiliop56** [comment]
@henrygd here is the pr #170 hope it's good!
