### ISSUE TITLE
Unable to add more than 8 systems via webui

### ISSUE THREAD

**Issue by beastarman74** [henrygd/beszel#88]
When attempting to add a 9th system via the Web interface it is not added to the application. The entered details disappear just like when a system is successfully added but does not appear.

There is no error in the webui and there is no error or info detailed in the docker logs. I have also checked the logs in Pocketbase and there is no logs.

I can add a system via the Pocketbase interface. This then appears in the Webui.

With the logs not showing anything is there any further information I can provide?

**Comment by henrygd** [comment]
Interesting!

Just to rule out auth issues, please log out and log back in to the Beszel interface.

Then could you please check the network tab in devtools to make sure that it sends a POST request to `/api/collections/systems/records` when you click "Add system"?

What's the status of your other systems? Are they all up / green?

**Comment by beastarman74** [comment]
You can close this. I started afresh and added all the machines and was able to add more than 8 without issue and they came online when I brought up the agent. I don't know what I did to cause the issue I was seeing.

Apologies for wasting your time. Thank you for your efforts with creating Beszel.

Paul.

**Comment by henrygd** [comment]
No worries, not a problem at all.

I only started working on this last month so it may very well have been a weird edge case bug that you were the first to encounter.
