### ISSUE TITLE
Beszel stopped collecting data and won't restart

### ISSUE THREAD

**Issue by Matthias-vdE** [henrygd/beszel#89]
Going to the web interface, the graphs for 1 hour, 12 hours, and 24 hours won't load. Looking at the graph for the past week, I noticed that Beszel stopped collection logs yesterday around 9PM.

![image](https://github.com/user-attachments/assets/767c3e2f-f67d-460e-b76e-861244dd3a18)

This happened on all of my systems. One has the agent running in Docker. The other two have the binary directly installed and are running as a service. I have restarted all (the agents as well as the webgui) to no avail.

Opening the page with F12 Dev Tools doesn't show any errors either.

Looking at the Pocketbase "backend", I see my three systems have indeed stopped reporting at around the same time:

![image](https://github.com/user-attachments/assets/2bc496ed-00cd-4a5b-a6ad-ecb0b5fab789)

Are there any other logs I can collect to troubleshoot this issue? The docker logs for both Beszel and the agent are not showing errors and confirm that everything is running.

**Comment by Matthias-vdE** [comment]
I have three systems in total. Two are servers running 24/7, the last one is my PC which is turned off most of the time.

I have now noticed the following: After pausing my PC (which is currently turned off), and then pausing and unpausing the servers, data collection has restarted.

![image](https://github.com/user-attachments/assets/109d6b61-a533-43fd-88a9-8ba8a7ae8f5e)

So it appears as if the collection doesn't work for any system if one of them is down and not in the paused state?

**Comment by henrygd** [comment]
Thanks for the detailed description and follow up.

I'll try to recreate that scenario today and fix the bug for the next release.

**Comment by henrygd** [comment]
Found and fixed. Should have the release out tomorrow if it runs properly for me overnight.

**Comment by henrygd** [comment]
0.1.2 out now with the fix. Let me know if you still see the problem after updating.

**Comment by Matthias-vdE** [comment]
Seems to be resolved indeed, I unpaused my PC which is turned off at the moment and all other servers are still sending their data.

Thanks!
