### ISSUE TITLE
Multiple notifications received for single alert event

### ISSUE THREAD

**Issue by roughnecks** [henrygd/beszel#97]
Hello,

I have set up beszel even on my desktop PC and tried email notifications when status is down. Problem is, beszel keeps sending those notifications endlessly, so it's a bit od a PITA if you're away and can't do anything to fix.

Maybe we can limit them to #number of emails and then stop?

Thanks

**Comment by henrygd** [comment]
Can you explain a bit further what you mean by sending endlessly?

Does it send a notification every minute for a down system even if the system doesn't go up in between notifications?

Behavior should be that it only triggers a notification if status changes between up and down.

**Comment by roughnecks** [comment]
A glitch maybe? at some point I had this:

![image](https://github.com/user-attachments/assets/83e4f914-31fe-4b04-a820-75bede540ff5)

> Does it send a notification every minute for a down system even if the system doesn't go up in between notifications?

will take agent down on my desktop now and let you know better

**Comment by roughnecks** [comment]
> Behavior should be that it only triggers a notification if status changes between up and down.

yeah, just tested and it worked like this ^
closing unless it happens again 👍

**Comment by henrygd** [comment]
Okay, awesome.

What's shown in the screenshot should definitely not be happening, so let me know if you see it again.

**Comment by roughnecks** [comment]
It just happened again: https://i.imgur.com/Yjww4C0.jpeg

**Comment by henrygd** [comment]
Someone else just had the issue in #129. If you still have logs in PocketBase for the last time this happened, can you check and see if you had the same situation with repeated i/o timeout errors?

Thanks!

**Comment by roughnecks** [comment]
Upgraded but I don't have logs anymore (5 days retention).
Will see next time

**Comment by henrygd** [comment]
This should be fixed now. Please let me know if it happens again!
